export type MarketplaceTaxonomyCategory = {
  stableId: string;
  publicSlug: string;
  label: string;
  headline: string;
  shortDescription: string;
  sortOrder: number;
  specialties: string[];
  editorNote?: string;
};

export type MarketplaceLegacyCategoryMapping = {
  nextStableId: string;
  impliedSpecialties?: string[];
  impliedServiceModes?: string[];
};

export const MARKETPLACE_TAXONOMY_CATEGORIES: readonly MarketplaceTaxonomyCategory[] = [
  {
    stableId: "personal_training",
    publicSlug: "personal-training",
    label: "Personal Training",
    headline: "Personal training",
    shortDescription: "Exercise instruction, coaching, and accountability for everyday fitness, strength, and body-composition goals.",
    sortOrder: 10,
    specialties: [
      "General Fitness",
      "Beginner Fitness",
      "Strength Training",
      "Muscle Building",
      "Hypertrophy Training",
      "Fat Loss",
      "Weight Management",
      "Body Recomposition",
      "Functional Fitness",
      "Conditioning",
      "Circuit Training",
      "HIIT",
      "Core Training",
      "Kettlebell Training",
      "Calisthenics",
      "Suspension Training",
      "Small Group Training",
      "Outdoor Training",
      "Home Training",
      "Gym-Based Training",
      "Men's Fitness",
      "Women's Fitness",
      "Senior Fitness",
      "Youth Fitness",
      "Prenatal Fitness",
      "Postpartum Fitness",
    ],
  },
  {
    stableId: "strength_conditioning",
    publicSlug: "strength-conditioning",
    label: "Strength & Conditioning",
    headline: "Strength and conditioning",
    shortDescription: "Performance-minded training for strength, power, speed, and resilient athletic development.",
    sortOrder: 20,
    specialties: [
      "Strength Development",
      "Strength & Conditioning",
      "General Strength Training",
      "Athletic Strength",
      "Explosive Power",
      "Speed Development",
      "Agility",
      "Conditioning",
      "Work Capacity",
      "Injury-Resilient Training",
      "Return-to-Performance Training",
      "Periodization",
      "Sports Conditioning",
      "Youth Athletic Development",
    ],
    editorNote: "Return-to-performance should not be represented as physical therapy or medical rehabilitation.",
  },
  {
    stableId: "bodybuilding_physique",
    publicSlug: "bodybuilding-physique",
    label: "Bodybuilding & Physique",
    headline: "Bodybuilding and physique coaching",
    shortDescription: "Coaching for muscle building, physique development, contest prep, and stage presentation.",
    sortOrder: 30,
    specialties: [
      "Bodybuilding",
      "Men's Physique",
      "Classic Physique",
      "Women's Bodybuilding",
      "Bikini",
      "Wellness",
      "Figure",
      "Women's Physique",
      "Competition Prep",
      "Contest Preparation",
      "Offseason Coaching",
      "Muscle Building",
      "Body Recomposition",
      "Fat Loss",
      "Posing",
      "Stage Presentation",
      "Peak Week Guidance",
      "Show-Day Preparation",
      "First-Time Competitors",
      "Advanced Competitors",
    ],
  },
  {
    stableId: "strength_sports",
    publicSlug: "strength-sports",
    label: "Strength Sports",
    headline: "Strength sports coaching",
    shortDescription: "Coaching for powerlifting, Olympic weightlifting, strongman, and strength competition prep.",
    sortOrder: 40,
    specialties: [
      "Powerlifting",
      "Olympic Weightlifting",
      "Strongman",
      "Strength Competition Preparation",
      "Powerlifting Meet Prep",
      "Weightlifting Competition Prep",
      "Strongman Competition Prep",
      "Squat Technique",
      "Bench Press Technique",
      "Deadlift Technique",
      "Olympic Lifting Technique",
      "Programming",
      "Peaking",
      "Strength Periodization",
    ],
  },
  {
    stableId: "running_endurance",
    publicSlug: "running-endurance",
    label: "Running & Endurance",
    headline: "Running and endurance coaching",
    shortDescription: "Structured support for running, endurance development, race preparation, and aerobic performance.",
    sortOrder: 50,
    specialties: [
      "Beginner Running",
      "5K Training",
      "10K Training",
      "Half Marathon",
      "Marathon",
      "Ultramarathon",
      "Trail Running",
      "Sprint Training",
      "Distance Running",
      "Running Technique",
      "Running Performance",
      "Endurance Training",
      "Triathlon",
      "Cycling",
      "Swimming for Endurance",
      "Cardiovascular Conditioning",
      "Race Preparation",
    ],
  },
  {
    stableId: "sports_performance",
    publicSlug: "sports-performance",
    label: "Sports Performance",
    headline: "Sports performance coaching",
    shortDescription: "Training focused on speed, explosiveness, conditioning, and sport-specific athletic performance.",
    sortOrder: 60,
    specialties: [
      "Athletic Performance",
      "Speed",
      "Agility",
      "Explosiveness",
      "Power Development",
      "Strength Development",
      "Conditioning",
      "Coordination",
      "Balance",
      "Sport-Specific Training",
      "Youth Athletic Development",
      "Adult Athletic Performance",
      "Combine Preparation",
      "Vertical Jump",
      "Sprint Performance",
    ],
  },
  {
    stableId: "nutrition",
    publicSlug: "nutrition",
    label: "Nutrition",
    headline: "Nutrition coaching",
    shortDescription: "Nutrition strategy, habit change, and food-structure support for health, body composition, and performance.",
    sortOrder: 70,
    specialties: [
      "General Nutrition",
      "Nutrition Coaching",
      "Healthy Eating",
      "Sports Nutrition",
      "Performance Nutrition",
      "Bodybuilding Nutrition",
      "Weight Management",
      "Fat-Loss Nutrition",
      "Muscle-Gain Nutrition",
      "Body Recomposition Nutrition",
      "Meal Planning",
      "Meal Preparation",
      "Habit-Based Nutrition",
      "Plant-Based Nutrition",
      "Vegetarian Nutrition",
      "Vegan Nutrition",
      "Nutrition Education",
      "Competition Nutrition",
      "Endurance Nutrition",
      "Strength-Sport Nutrition",
    ],
    editorNote: "Do not represent regulated nutrition titles unless they are supported by verified credentials.",
  },
  {
    stableId: "dietetics",
    publicSlug: "dietetics",
    label: "Dietetics",
    headline: "Dietetics support",
    shortDescription: "Credentialed dietetics support where regulated nutrition credentials materially matter.",
    sortOrder: 80,
    specialties: [
      "General Dietetics",
      "Sports Dietetics",
      "Performance Nutrition",
      "Weight Management",
      "Plant-Based Nutrition",
      "Vegetarian Nutrition",
      "Nutrition Education",
      "Healthy Eating",
      "Athletic Nutrition",
    ],
    editorNote: "Only verified credentials should drive titles like Registered Dietitian or RDN.",
  },
  {
    stableId: "health_wellness_coaching",
    publicSlug: "health-wellness-coaching",
    label: "Health & Wellness Coaching",
    headline: "Health and wellness coaching",
    shortDescription: "Support for sustainable habits, accountability, lifestyle structure, and general wellbeing.",
    sortOrder: 90,
    specialties: [
      "Health Coaching",
      "Wellness Coaching",
      "Lifestyle Coaching",
      "Healthy Habit Development",
      "Behavior Change",
      "Accountability",
      "Goal Setting",
      "Lifestyle Improvement",
      "Healthy Aging",
      "Work-Life Wellness",
      "Wellness Planning",
      "Sustainable Lifestyle Change",
      "General Wellbeing",
      "Fitness Accountability",
      "Nutrition Accountability",
    ],
  },
  {
    stableId: "life_mindset_coaching",
    publicSlug: "life-mindset-coaching",
    label: "Life & Mindset Coaching",
    headline: "Life and mindset coaching",
    shortDescription: "Coaching centered on motivation, confidence, accountability, and personal growth.",
    sortOrder: 100,
    specialties: [
      "Life Coaching",
      "Mindset Coaching",
      "Confidence Coaching",
      "Goal Setting",
      "Accountability",
      "Personal Development",
      "Motivation",
      "Habit Development",
      "Performance Mindset",
      "Mental Performance",
      "Productivity Coaching",
      "Career-Life Balance",
      "Lifestyle Change",
      "Personal Growth",
    ],
    editorNote: "These services should not be described as psychotherapy, counseling, or medical care.",
  },
  {
    stableId: "yoga",
    publicSlug: "yoga",
    label: "Yoga",
    headline: "Yoga",
    shortDescription: "Yoga instruction for movement, flexibility, breath, and mind-body practice.",
    sortOrder: 110,
    specialties: [
      "Beginner Yoga",
      "Hatha Yoga",
      "Vinyasa Yoga",
      "Power Yoga",
      "Restorative Yoga",
      "Yin Yoga",
      "Prenatal Yoga",
      "Postnatal Yoga",
      "Yoga for Athletes",
      "Yoga for Mobility",
      "Yoga for Flexibility",
      "Private Yoga",
      "Group Yoga",
      "Breath-Focused Yoga",
      "Meditation-Focused Yoga",
    ],
  },
  {
    stableId: "pilates",
    publicSlug: "pilates",
    label: "Pilates",
    headline: "Pilates",
    shortDescription: "Pilates instruction for strength, control, posture, and movement quality.",
    sortOrder: 120,
    specialties: [
      "Beginner Pilates",
      "Mat Pilates",
      "Reformer Pilates",
      "Private Pilates",
      "Group Pilates",
      "Pilates for Strength",
      "Pilates for Mobility",
      "Pilates for Flexibility",
      "Athletic Pilates",
      "Prenatal Pilates",
      "Postnatal Pilates",
      "Core Strength",
      "Posture & Movement",
    ],
  },
  {
    stableId: "mobility_movement",
    publicSlug: "mobility-movement",
    label: "Mobility, Flexibility & Movement",
    headline: "Mobility, flexibility, and movement coaching",
    shortDescription: "Support for mobility, flexibility, movement quality, and non-medical corrective exercise.",
    sortOrder: 130,
    specialties: [
      "Mobility Training",
      "Flexibility Training",
      "Assisted Stretching",
      "Stretching",
      "Movement Coaching",
      "Movement Quality",
      "Corrective Exercise",
      "Posture & Movement",
      "Joint Mobility",
      "Athletic Mobility",
      "Functional Movement",
      "Range-of-Motion Training",
      "Mobility for Lifters",
      "Mobility for Runners",
      "Mobility for Athletes",
    ],
    editorNote: "Do not represent this category as physical therapy or medical rehabilitation.",
  },
  {
    stableId: "mindfulness_breathwork",
    publicSlug: "mindfulness-breathwork",
    label: "Meditation, Mindfulness & Breathwork",
    headline: "Meditation, mindfulness, and breathwork",
    shortDescription: "Breath, mindfulness, and meditation support for focus, relaxation, and everyday regulation.",
    sortOrder: 140,
    specialties: [
      "Meditation",
      "Guided Meditation",
      "Mindfulness",
      "Breathwork",
      "Relaxation",
      "Stress Management",
      "Meditation for Beginners",
      "Meditation for Athletes",
      "Performance Mindfulness",
      "Mindful Living",
      "Focus & Concentration",
      "Sleep Relaxation Practices",
      "Breath Awareness",
    ],
    editorNote: "Do not represent this category as treatment for mental-health or medical conditions.",
  },
  {
    stableId: "recovery_bodywork",
    publicSlug: "recovery-bodywork",
    label: "Recovery & Bodywork",
    headline: "Recovery and bodywork",
    shortDescription: "Recovery-oriented services such as massage, assisted stretching, and non-medical bodywork support.",
    sortOrder: 150,
    specialties: [
      "Massage Therapy",
      "Sports Massage",
      "Assisted Stretching",
      "Recovery Sessions",
      "Mobility Recovery",
      "Soft-Tissue Bodywork",
      "Athletic Recovery",
      "Relaxation Massage",
      "Recovery Coaching",
    ],
    editorNote: "Licensed or regulated designations should only be shown when supported by verified credentials.",
  },
  {
    stableId: "special_population_fitness",
    publicSlug: "special-population-fitness",
    label: "Special Population Fitness",
    headline: "Special population fitness",
    shortDescription: "Fitness support for clients who need a lower-impact, age-aware, or more adaptive training approach.",
    sortOrder: 160,
    specialties: [
      "Senior Fitness",
      "Active Aging",
      "Youth Fitness",
      "Adaptive Fitness",
      "Prenatal Fitness",
      "Postpartum Fitness",
      "Beginner Fitness",
      "Low-Impact Fitness",
      "Plus-Size Fitness",
      "Inclusive Fitness",
      "Fitness for People with Disabilities",
      "Balance Training",
      "Functional Independence",
      "Healthy Aging",
    ],
    editorNote: "Do not imply medical treatment, rehabilitation, or disease management.",
  },
] as const;

export const MARKETPLACE_CLIENT_GOAL_TAGS = [
  "Build Muscle",
  "Weight Loss / Fat Loss",
  "Get Stronger",
  "Body Recomposition",
  "Improve Fitness & Conditioning",
  "Improve Endurance",
  "Improve Running",
  "Prepare for a Race",
  "Prepare for a Competition",
  "Improve Athletic Performance",
  "Mobility & Flexibility",
  "Improve Nutrition",
  "Healthy Habits & Lifestyle",
  "Accountability",
  "Improve Confidence",
  "Stress & Mindfulness",
  "General Wellness",
  "Healthy Aging",
  "Learn / Return to Exercise",
  "Other",
] as const;

export const MARKETPLACE_LEGACY_CATEGORY_MAPPINGS: Record<string, MarketplaceLegacyCategoryMapping> = {
  personal_training: { nextStableId: "personal_training" },
  "personal-trainers": { nextStableId: "personal_training" },
  competition_prep: { nextStableId: "bodybuilding_physique", impliedSpecialties: ["Competition Prep"] },
  "competition-prep": { nextStableId: "bodybuilding_physique", impliedSpecialties: ["Competition Prep"] },
  online_coaching: { nextStableId: "personal_training", impliedServiceModes: ["online"] },
  "online-coaches": { nextStableId: "personal_training", impliedServiceModes: ["online"] },
  strength_coaching: { nextStableId: "strength_conditioning", impliedSpecialties: ["Strength & Conditioning"] },
  "strength-coaches": { nextStableId: "strength_conditioning", impliedSpecialties: ["Strength & Conditioning"] },
  bodybuilding_coaching: { nextStableId: "bodybuilding_physique", impliedSpecialties: ["Bodybuilding"] },
  "bodybuilding-coaches": { nextStableId: "bodybuilding_physique", impliedSpecialties: ["Bodybuilding"] },
  powerlifting_coaching: { nextStableId: "strength_sports", impliedSpecialties: ["Powerlifting"] },
  "powerlifting-coaches": { nextStableId: "strength_sports", impliedSpecialties: ["Powerlifting"] },
  running_coaching: { nextStableId: "running_endurance", impliedSpecialties: ["Running Performance"] },
  "running-coaches": { nextStableId: "running_endurance", impliedSpecialties: ["Running Performance"] },
  nutrition_professionals: { nextStableId: "nutrition", impliedSpecialties: ["General Nutrition"] },
  "nutrition-professionals": { nextStableId: "nutrition", impliedSpecialties: ["General Nutrition"] },
  nutrition_coaching: { nextStableId: "nutrition", impliedSpecialties: ["Nutrition Coaching"] },
  "nutrition-coaches": { nextStableId: "nutrition", impliedSpecialties: ["Nutrition Coaching"] },
  dietitians: { nextStableId: "dietetics" },
  lifestyle_coaching: { nextStableId: "life_mindset_coaching", impliedSpecialties: ["Life Coaching"] },
  "life-coaches": { nextStableId: "life_mindset_coaching", impliedSpecialties: ["Life Coaching"] },
  health_coaching: { nextStableId: "health_wellness_coaching", impliedSpecialties: ["Health Coaching"] },
  "health-coaches": { nextStableId: "health_wellness_coaching", impliedSpecialties: ["Health Coaching"] },
  wellness_coaching: { nextStableId: "health_wellness_coaching", impliedSpecialties: ["Wellness Coaching"] },
  "wellness-coaches": { nextStableId: "health_wellness_coaching", impliedSpecialties: ["Wellness Coaching"] },
  yoga: { nextStableId: "yoga" },
  "yoga-instructors": { nextStableId: "yoga" },
  pilates: { nextStableId: "pilates" },
  "pilates-instructors": { nextStableId: "pilates" },
  mobility_coaching: { nextStableId: "mobility_movement", impliedSpecialties: ["Mobility Training"] },
  "mobility-coaches": { nextStableId: "mobility_movement", impliedSpecialties: ["Mobility Training"] },
  stretching_flexibility: { nextStableId: "mobility_movement", impliedSpecialties: ["Flexibility Training"] },
  "stretching-flexibility": { nextStableId: "mobility_movement", impliedSpecialties: ["Flexibility Training"] },
  meditation: { nextStableId: "mindfulness_breathwork", impliedSpecialties: ["Meditation"] },
  "meditation-coaches": { nextStableId: "mindfulness_breathwork", impliedSpecialties: ["Meditation"] },
  breathwork: { nextStableId: "mindfulness_breathwork", impliedSpecialties: ["Breathwork"] },
  "breathwork-coaches": { nextStableId: "mindfulness_breathwork", impliedSpecialties: ["Breathwork"] },
  sports_performance: { nextStableId: "sports_performance" },
  "sports-performance": { nextStableId: "sports_performance" },
};

export const MARKETPLACE_CATEGORY_RELATED_PUBLIC_SLUGS: Record<string, string[]> = {
  "personal-training": ["strength-conditioning", "nutrition", "health-wellness-coaching", "special-population-fitness"],
  "strength-conditioning": ["personal-training", "sports-performance", "strength-sports", "bodybuilding-physique"],
  "bodybuilding-physique": ["nutrition", "strength-conditioning", "strength-sports", "personal-training"],
  "strength-sports": ["strength-conditioning", "bodybuilding-physique", "personal-training"],
  "running-endurance": ["sports-performance", "nutrition", "health-wellness-coaching"],
  "sports-performance": ["strength-conditioning", "running-endurance", "personal-training"],
  nutrition: ["dietetics", "health-wellness-coaching", "bodybuilding-physique"],
  dietetics: ["nutrition", "health-wellness-coaching"],
  "health-wellness-coaching": ["nutrition", "life-mindset-coaching", "personal-training"],
  "life-mindset-coaching": ["health-wellness-coaching", "mindfulness-breathwork"],
  yoga: ["mobility-movement", "pilates", "mindfulness-breathwork"],
  pilates: ["mobility-movement", "yoga", "special-population-fitness"],
  "mobility-movement": ["yoga", "pilates", "recovery-bodywork", "special-population-fitness"],
  "mindfulness-breathwork": ["life-mindset-coaching", "yoga", "recovery-bodywork"],
  "recovery-bodywork": ["mobility-movement", "mindfulness-breathwork", "health-wellness-coaching"],
  "special-population-fitness": ["personal-training", "mobility-movement", "health-wellness-coaching"],
};

const taxonomyByStableId = new Map(
  MARKETPLACE_TAXONOMY_CATEGORIES.map((category) => [category.stableId, category]),
);
const taxonomyByPublicSlug = new Map(
  MARKETPLACE_TAXONOMY_CATEGORIES.map((category) => [category.publicSlug, category]),
);

export function getMarketplaceTaxonomyCategoryByStableId(stableId: string | null | undefined) {
  return stableId ? taxonomyByStableId.get(stableId) ?? null : null;
}

export function getMarketplaceTaxonomyCategoryByPublicSlug(publicSlug: string | null | undefined) {
  return publicSlug ? taxonomyByPublicSlug.get(publicSlug) ?? null : null;
}

export function getMarketplaceLegacyCategoryMapping(identifier: string | null | undefined) {
  return identifier ? MARKETPLACE_LEGACY_CATEGORY_MAPPINGS[identifier] ?? null : null;
}

export function resolveMarketplaceCategoryTaxonomy(
  stableId: string | null | undefined,
  publicSlug: string | null | undefined,
) {
  return getMarketplaceTaxonomyCategoryByStableId(stableId)
    ?? getMarketplaceTaxonomyCategoryByPublicSlug(publicSlug)
    ?? getMarketplaceTaxonomyCategoryByStableId(getMarketplaceLegacyCategoryMapping(stableId)?.nextStableId ?? null)
    ?? getMarketplaceTaxonomyCategoryByStableId(getMarketplaceLegacyCategoryMapping(publicSlug)?.nextStableId ?? null)
    ?? null;
}

export function getMarketplaceTaxonomySelections(categoryStableIds: string[]) {
  return categoryStableIds
    .map((stableId) => getMarketplaceTaxonomyCategoryByStableId(stableId))
    .filter((category): category is MarketplaceTaxonomyCategory => Boolean(category));
}
