import type { CatalogMessages } from "../../lib/i18n/catalog-types.ts";

const messages: CatalogMessages = {
  exercise: {
    seo: {
      indexTitle: "Exercise Database",
      indexDescription: "Explore a beginner-friendly exercise database with muscles worked, equipment, instructions, and related training guidance.",
      categoryFallbackTitle: "Exercise category",
      categoryFallbackDescription: "Browse exercises by muscle group and equipment.",
      detailTitle: "{name}: Form & Muscles Worked",
      detailDescription: "Learn how to perform {name}, including the muscles worked, equipment, instructions, benefits, and common mistakes.",
    },
    index: {
      eyebrow: "Exercises", title: "Browse exercises by muscle group, equipment, and movement.", intro: "Explore beginner-friendly exercise pages with instructions, benefits, common mistakes, and related movements you can track in Logbook.", browseWorkouts: "Browse workout templates", learnLogbook: "Learn about Logbook", countLabel: "Exercises", countCopy: "Public movements available in the current exercise library.", categoriesLabel: "Category links", categoriesValue: "Muscle + equipment", categoriesCopy: "Jump directly into chest, back, legs, dumbbell, barbell, and more.", purposeLabel: "Use case", purposeValue: "Training clarity", purposeCopy: "Find the movement, learn the basics, and track it inside Logbook.", popularEyebrow: "Popular exercises", popularTitle: "Start with the exercise pages people need most.", popularCopy: "These commonly used movements are a practical place to begin before exploring the full database.", musclesEyebrow: "Muscle groups", musclesTitle: "Start with what you want to train.", musclesCopy: "Browse exercise categories for the main muscle groups people search first.", equipmentEyebrow: "Equipment", equipmentTitle: "Filter the library by what you have available.", equipmentCopy: "Find useful options for barbells, dumbbells, cables, machines, kettlebells, or bodyweight training.", exploreCategory: "Explore {category} exercises", emptyLabel: "Exercise library", emptyTitle: "The public exercise database is being refreshed.", emptyCopy: "Once the exercise library finishes syncing, the movements will appear here automatically.",
    },
    directory: { eyebrow: "Exercise finder", title: "Search by name, muscle group, or equipment.", copy: "Browse by what you want to train, the equipment you have, or a specific movement.", searchLabel: "Search exercises", searchPlaceholder: "Search bench press, lunge, row...", muscleLabel: "Muscle group", allMuscles: "All muscle groups", equipmentLabel: "Equipment", allEquipment: "All equipment", resultSingular: "exercise", resultPlural: "exercises", resultCopy: "Use the filters to create a more useful shortlist.", empty: "No exercises matched that search. Try a broader muscle group, a simpler movement name, or different equipment." },
    category: { muscleEyebrow: "Muscle group", equipmentEyebrow: "Equipment", results: "Results", resultsCopy: "Exercises where this is the primary training focus.", purpose: "Use case", purposeValue: "Find your next option", purposeCopy: "Compare similar movements without searching the entire database.", track: "Track it", trackValue: "Built for Logbook", trackCopy: "Find the exercise, then track it in Logbook.", guideEyebrow: "Category guide", guideTitle: "How to use this {category} exercise category.", guideParagraphs: ["Use this page to narrow the library to movements that match the muscle group or equipment you want to use.", "Choose a small number of exercises that fit your goal, current ability, and available setup. Repeatable movements are easier to learn and track.", "Technique, range of motion, and load should match your experience. Start conservatively and increase difficulty only when you can keep the movement controlled."], topEyebrow: "Top exercises", topTitle: "Ten useful places to start in this category.", topCopy: "Begin with these commonly used exercises before scanning the full list.", supportingEyebrow: "Supporting matches", supportingTitle: "Exercises that also train {category}.", supportingCopy: "These are not primary {category} movements, but they involve the area as a secondary focus.", faqEyebrow: "FAQ", faqTitle: "Common questions about {category} exercises.", faqs: [{ question: "How many exercises should I choose?", answer: "Most sessions only need a focused group of movements. Choose enough to train the target area without adding work you cannot recover from or repeat consistently." }, { question: "How should I choose the right exercise?", answer: "Match the movement to your goal, experience, equipment, comfort, and ability to use controlled technique." }, { question: "Should I change exercises every week?", answer: "Usually not. Keeping key movements consistent makes it easier to learn technique and measure progress." }, { question: "What if an exercise causes pain?", answer: "Stop the movement and choose a comfortable alternative. Persistent or concerning pain should be discussed with a qualified healthcare professional." }] },
    detail: { eyebrow: "Exercise guide", primaryMuscle: "Primary muscle", primaryMuscleCopy: "The main muscle group listed for this exercise.", equipment: "Equipment", equipmentCopy: "The equipment listed for this variation.", difficulty: "Difficulty", difficultyCopy: "The recorded setup and movement complexity.", musclesWorked: "Muscles worked", secondaryMuscles: "{name} also involves {muscles}.", noSecondaryMuscles: "No secondary muscle group is listed for this variation.", exerciseType: "Exercise type", movementPattern: "Movement pattern: {pattern}.", compound: "This is a compound exercise.", isolation: "This is an isolation exercise.", trainingLevel: "Training level", trainingLevelCopy: "This level reflects the setup and movement complexity recorded for this exercise.", instructions: "Instructions", howTo: "How to do {name}", benefits: "Benefits", mistakes: "Common mistakes", variations: "Variations", alternatives: "Alternatives", relatedEyebrow: "Related exercises", relatedTitle: "More exercises in the same category.", relatedCopy: "Use these for a similar movement pattern, a different setup, or another option for the same target area.", faqEyebrow: "FAQ", faqTitle: "Common questions about {name}.", faqQuestions: ["What muscles does {name} work?", "What equipment does {name} use?", "Is {name} a compound exercise?", "How should I use {name} in a workout?"], faqAnswers: ["The primary muscle group is {primary}. Secondary muscles may include {secondary}.", "This variation uses {equipment}.", "{compound}", "Use a controlled load and repeatable technique that fits your training plan and experience level."] },
    card: { view: "View exercise" },
    labels: { allLevels: "All levels", generalExercise: "General exercise", generalMovement: "General", fullBody: "Full body", minimalEquipment: "Minimal", muscles: { chest: "Chest", back: "Back", legs: "Legs", shoulders: "Shoulders", arms: "Arms", core: "Core", glutes: "Glutes" }, equipment: { barbell: "Barbell", dumbbell: "Dumbbell", cable: "Cable", machine: "Machine", bodyweight: "Bodyweight", kettlebell: "Kettlebell", "ez-bar": "EZ bar", "exercise-ball": "Exercise ball", "foam-roll": "Foam roller", "medicine-ball": "Medicine ball", bands: "Resistance bands" }, difficulty: { beginner: "Beginner", intermediate: "Intermediate", advanced: "Advanced" }, exerciseTypes: { strength: "Strength", stretching: "Stretching", cardio: "Cardio", plyometrics: "Plyometrics", "olympic-weightlifting": "Olympic weightlifting" }, movementPatterns: { "horizontal-push": "Horizontal push", horizontal_push: "Horizontal push", "vertical-push": "Vertical push", vertical_push: "Vertical push", "horizontal-pull": "Horizontal pull", horizontal_pull: "Horizontal pull", "vertical-pull": "Vertical pull", vertical_pull: "Vertical pull", squat: "Squat", hinge: "Hinge", lunge: "Lunge", carry: "Carry", rotation: "Rotation", "elbow-flexion": "Elbow flexion", elbow_flexion: "Elbow flexion", "elbow-extension": "Elbow extension", elbow_extension: "Elbow extension", "single-leg": "Single-leg" } },
    disclaimer: { label: "Disclaimer", message: "Exercise involves risk of injury. Use appropriate technique, equipment, and judgment, and choose activities appropriate for your abilities. This content is for general informational purposes and is not medical advice." },
    cta: { indexTitle: "Want to track your exercises for free in Logbook?", indexCopy: "Use Logbook to record sets, reps, weights, and workout history once you find the movements you want to repeat.", categoryTitle: "Track this exercise category for free in Logbook.", categoryCopy: "Save the work, review progress, and make clearer training decisions in Logbook.", detailTitle: "Track this exercise for free in Logbook.", detailCopy: "Record sets, reps, load, and progress without guessing what happened last week." },
  },
  nutrition: {
    seo: { indexTitle: "Restaurant Nutrition Facts & Macros", indexDescription: "Search restaurant nutrition facts and compare calories, protein, carbohydrates, fat, and serving sizes.", restaurantTitle: "{restaurant} Nutrition Facts", restaurantDescription: "Explore {restaurant} nutrition facts, calories, protein, carbohydrates, fat, and serving sizes across menu items.", methodologyTitle: "Restaurant Nutrition Data Methodology", methodologyDescription: "Learn how ElevareFit organizes restaurant nutrition data and presents calorie and macro estimates responsibly." },
    index: { eyebrow: "Nutrition", title: "Restaurant nutrition facts and macros.", intro: "Search restaurants, compare menu items, and review calories, protein, carbohydrates, and fat before you order.", highProteinCta: "Explore high-protein fast food options", calculatorCta: "Open calorie calculator", restaurants: "Restaurants", restaurantsCopy: "Public restaurant nutrition guides you can search and compare.", items: "Menu items", itemsCopy: "Calories and macros from the current restaurant nutrition dataset.", popularSearches: "Popular searches", popularValue: "Fast food and chains", popularCopy: "Explore common restaurant searches or specific menu items.", popularEyebrow: "Popular restaurants", popularTitle: "Start with the restaurants people search most.", popularSectionCopy: "Open a restaurant nutrition page, then use search and filters to compare menu items.", quickLinksTitle: "Quick links to restaurant nutrition facts.", quickLinksCopy: "Go directly to featured restaurant guides and compare nutrition facts." },
    search: { eyebrow: "Search", title: "Search restaurants and menu items.", copy: "Search by restaurant name or go directly to menu items and their macros.", restaurantsLabel: "Search restaurants", restaurantsPlaceholder: "Chipotle, Subway, Starbucks...", itemsLabel: "Search menu items", itemsPlaceholder: "Chicken bowl, grilled nuggets...", noRestaurants: "No restaurants matched that search.", typeMore: "Type at least 2 characters to search menu items.", loading: "Loading menu item search...", unavailable: "Menu item search is temporarily unavailable. Try again.", noItems: "No menu items matched that search.", itemSingular: "item", itemPlural: "items", at: "at", caloriesShort: "cal", protein: "protein", carbs: "carbs", fat: "fat" },
    restaurant: { eyebrow: "Restaurant nutrition", headline: "{restaurant} nutrition facts.", intro: "Search, filter, and compare calories, protein, carbohydrates, fat, and serving size across {restaurant} menu items.", highProteinCta: "See highest protein items", under500Cta: "See items under 500 calories", menuItems: "Menu items", menuItemsCopy: "Public items currently available in this restaurant nutrition guide.", categories: "Categories", categoriesCopy: "Use category filters to narrow the menu faster.", macros: "Macros", macrosValue: "Calories, protein, carbs, fat", macrosCopy: "Sort by the macro view that best matches your goal.", moreViews: "More {restaurant} nutrition views", moreViewsCopy: "Compare higher-protein, lower-calorie, lower-carb, and under-500-calorie options.", moreRestaurants: "More restaurant nutrition facts", moreRestaurantsCopy: "Keep exploring related restaurant guides and compare more menus.", relatedTools: "Related tools", relatedToolsCopy: "Estimate calories, protein, macros, and body fat alongside menu planning." },
    variant: { restaurantEyebrow: "Restaurant nutrition", fastFoodEyebrow: "Fast food nutrition", allFacts: "View all nutrition facts", anotherView: "Explore another nutrition view", itemsInView: "Items in this view", itemsInViewCopy: "Filtered menu items in this nutrition view.", restaurantItems: "Restaurant menu items", restaurantItemsCopy: "Compare this filtered view with the full menu.", sortOptions: "Sort options", sortValue: "Protein, calories, carbs, fat", sortCopy: "Re-sort the list to compare macro tradeoffs.", popularRestaurants: "Popular restaurants", popularRestaurantsTitle: "Popular fast food restaurants in this nutrition view.", popularRestaurantsCopy: "Open restaurant-specific nutrition pages to compare a menu more closely.", fastFoodGuides: "More fast food nutrition guides", fastFoodGuidesCopy: "Switch between higher-protein, lower-calorie, and under-500-calorie views." },
    explorer: { variants: { all: "All items", "high-protein": "High protein", "low-calorie": "Low calorie", "under-500-calories": "Under 500 calories", "low-carb": "Low carb" }, title: "Filter and sort menu items.", copy: "Sort by calories, protein, carbohydrates, fat, or protein per calorie and narrow the list to your goal.", searchLabel: "Search items", searchPlaceholder: "Search menu items", category: "Category", allCategories: "All categories", maxCalories: "Max calories", minProtein: "Min protein", maxCarbs: "Max carbs", maxFat: "Max fat", hideExtras: "Hide drinks, sauces, toppings, and add-ons", sort: "Sort", sortOptions: { "lowest-calories": "Lowest calories", "highest-calories": "Highest calories", "highest-protein": "Highest protein", "highest-protein-per-calorie": "Highest protein per calorie", "lowest-carbs": "Lowest carbs", "lowest-fat": "Lowest fat" }, itemSingular: "item", itemPlural: "items", total: "{count} total in this view", empty: "No items matched the current filters. Adjust the search or macro filters and try again.", restaurant: "Restaurant", item: "Item", serving: "Serving size", calories: "Calories", protein: "Protein", carbs: "Carbs", fat: "Fat", proteinPerCalorie: "Protein / Cal", tags: "Tags", servingVaries: "Serving varies", tagLabels: { "High Protein": "High Protein", "Very High Protein": "Very High Protein", "Low Calorie": "Low Calorie", "Very Low Calorie": "Very Low Calorie", "Low Carb": "Low Carb", "Low Fat": "Low Fat" } },
    card: { itemSingular: "item", itemPlural: "items", description: "Explore calories, protein, carbohydrates, and fat across {count} menu items.", view: "View nutrition facts" },
    links: { eyebrow: "Related nutrition links", popularSearches: "Popular nutrition searches", popularSearchesCopy: "Explore common restaurant nutrition pages and curated macro views.", fastFoodGuides: "Fast food nutrition guides", fastFoodGuidesCopy: "Compare fast food items by protein, calories, and lighter options.", relatedTools: "Related tools", relatedToolsCopy: "Estimate calories, protein, macros, and body fat alongside restaurant menu comparisons." },
    methodology: { eyebrow: "Nutrition transparency", title: "How restaurant nutrition data is handled.", intro: "ElevareFit organizes restaurant calorie and macro information to make menu comparisons easier. This page explains what the data represents and what you should verify directly.", browse: "Browse nutrition facts", sections: [{ title: "Data sources", body: "Nutrition records are compiled from publicly available restaurant and product information. ElevareFit does not independently laboratory-test restaurant products." }, { title: "Serving sizes and custom orders", body: "Values apply to the listed item and serving. Portions, recipes, preparation, substitutions, toppings, sauces, and customizations can change actual nutrition." }, { title: "Updates and menu changes", body: "Restaurant menus and recipes change. A database update date does not guarantee that a restaurant has not changed an item since publication." }, { title: "How comparisons are calculated", body: "Curated views filter and sort available records. They are comparison tools, not endorsements or personalized recommendations. Missing values are not inferred as zero." }, { title: "Allergies, medical conditions, and verification", body: "Do not use this database to determine whether an item is safe for an allergy or medical condition. Confirm ingredients, allergens, and preparation directly with the restaurant." }] },
    disclaimer: { label: "Disclaimer", paragraphs: ["Nutrition information is provided for informational purposes and may vary by location, preparation, serving size, recipe, menu updates, and customization. Verify information directly with the restaurant when accuracy is important.", "Elevare does not guarantee that nutrition information is complete, current, or error-free.", "Do not rely on this information to determine whether a food is safe for a food allergy or medical condition. Contact the restaurant directly about ingredients and allergens.", "Third-party names and trademarks are the property of their respective owners. ElevareFit is not affiliated with or endorsed by these companies unless expressly stated."], methodologyLink: "Read how ElevareFit handles restaurant nutrition data." },
    cta: { label: "Track with Logbook", title: "Track your nutrition with Logbook", copy: "Track calories, macros, weight, workouts, and progress for free." },
  },
};

export default messages;
