import { createHash } from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { LEGAL_DOCUMENTS } from "../lib/legal.ts";

const projectRoot = process.cwd();
const repositoryRoot = path.resolve(projectRoot, "..");
const isInitialize = process.argv.includes("--initialize");

type LegalDocumentRecord = {
  documentKey: string;
  version: string;
  effectiveDate: string;
  archivePath: string;
  sha256: string;
};

function hashContent(content: Buffer) {
  return createHash("sha256").update(content).digest("hex");
}

async function buildRecord(document: (typeof LEGAL_DOCUMENTS)[keyof typeof LEGAL_DOCUMENTS]) {
  const sourceFilename = document.key === "terms_of_service" ? "terms-of-service.html" : "privacy-policy.html";
  const sourcePath = path.join(projectRoot, "content", "legal", sourceFilename);
  const archiveFilePath = path.join(projectRoot, "public", document.archivePath.replace(/^\//, ""));
  const activeRouteFilePath = path.join(
    projectRoot,
    "public",
    document.activePath.replace(/^\//, ""),
    "index.html",
  );
  const sourceContent = await fs.readFile(sourcePath);

  if (isInitialize) {
    await fs.mkdir(path.dirname(archiveFilePath), { recursive: true });
    try {
      const archivedContent = await fs.readFile(archiveFilePath);
      if (!archivedContent.equals(sourceContent)) {
        throw new Error(`Archived ${document.key} content differs from the active document for version ${document.version}. Bump the legal version instead of overwriting history.`);
      }
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
      await fs.writeFile(archiveFilePath, sourceContent);
    }

    await fs.mkdir(path.dirname(activeRouteFilePath), { recursive: true });
    await fs.writeFile(activeRouteFilePath, sourceContent);
  }

  const archivedContent = await fs.readFile(archiveFilePath);
  if (!archivedContent.equals(sourceContent)) {
    throw new Error(`Active ${document.key} content changed without a legal version bump.`);
  }

  const activeRouteContent = await fs.readFile(activeRouteFilePath);
  if (!activeRouteContent.equals(sourceContent)) {
    throw new Error(`Generated clean route for ${document.key} is stale. Run npm run legal:archive.`);
  }

  return {
    documentKey: document.key,
    version: document.version,
    effectiveDate: document.effectiveDate,
    archivePath: document.archivePath,
    sha256: hashContent(archivedContent),
  } satisfies LegalDocumentRecord;
}

function buildSeedMigration(records: LegalDocumentRecord[]) {
  const values = records.map((record) =>
    `  ('${record.documentKey}', '${record.version}', '${record.effectiveDate}'::date, '${record.sha256}', '${record.archivePath}')`,
  ).join(",\n");

  return `-- Generated by website/scripts/generate-legal-archive.ts. Do not edit hashes manually.\n\nbegin;\n\ndo $legal_snapshot$\nbegin\n  if exists (\n    select 1\n    from public.legal_document_versions as current_version\n    join (values\n${values}\n    ) as expected(document_key, version, effective_date, content_sha256, archive_path)\n      on expected.document_key = current_version.document_key\n      and expected.version = current_version.version\n    where current_version.effective_date is distinct from expected.effective_date\n      or current_version.content_sha256 is distinct from expected.content_sha256\n      or current_version.archive_path is distinct from expected.archive_path\n  ) then\n    raise exception 'An existing legal document version differs from the immutable release snapshot.';\n  end if;\nend\n$legal_snapshot$;\n\ninsert into public.legal_document_versions (\n  document_key,\n  version,\n  effective_date,\n  content_sha256,\n  archive_path\n)\nvalues\n${values}\non conflict (document_key, version) do nothing;\n\nupdate public.user_legal_acceptances as acceptance\nset legal_document_version_id = version.id\nfrom public.legal_document_versions as version\nwhere version.document_key = acceptance.document_key\n  and version.version = acceptance.document_version\n  and acceptance.legal_document_version_id is distinct from version.id;\n\nupdate public.user_legal_acceptance_history as history\nset terms_document_version_id = version.id\nfrom public.legal_document_versions as version\nwhere history.terms_version = version.version\n  and version.document_key = 'terms_of_service'\n  and history.terms_document_version_id is distinct from version.id;\n\nupdate public.user_legal_acceptance_history as history\nset privacy_document_version_id = version.id\nfrom public.legal_document_versions as version\nwhere history.privacy_version = version.version\n  and version.document_key = 'privacy_policy'\n  and history.privacy_document_version_id is distinct from version.id;\n\ncommit;\n`;
}

const records = await Promise.all(Object.values(LEGAL_DOCUMENTS).map(buildRecord));
const manifestPath = path.join(projectRoot, "public", "legal", "legal-document-versions.json");
const manifest = `${JSON.stringify({ generatedFrom: "immutable legal archive", documents: records }, null, 2)}\n`;

if (isInitialize) {
  await fs.mkdir(path.dirname(manifestPath), { recursive: true });
  await fs.writeFile(manifestPath, manifest);
  await fs.writeFile(
    path.join(repositoryRoot, "supabase", "migrations", "20260820211000_seed_legal_document_versions.sql"),
    buildSeedMigration(records),
  );
} else {
  const existingManifest = await fs.readFile(manifestPath, "utf8");
  if (existingManifest !== manifest) {
    throw new Error("Legal archive manifest is stale. Run npm run legal:archive after intentionally versioning the documents.");
  }
}

console.log(`${isInitialize ? "Generated" : "Verified"} ${records.length} immutable legal document records.`);
