import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const roots = [path.join(root, "app"), path.join(root, "components")];
const excludedSegments = [
  `${path.sep}api${path.sep}`,
  `${path.sep}[locale]${path.sep}`,
  `${path.sep}localization${path.sep}`,
];
const candidates: string[] = [];

function walk(directory: string): string[] {
  return fs.readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const target = path.join(directory, entry.name);
    if (excludedSegments.some((segment) => target.includes(segment))) return [];
    if (entry.isDirectory()) return walk(target);
    return /\.(?:ts|tsx)$/.test(entry.name) ? [target] : [];
  });
}

const jsxText = />([^<>{}\n][^<>{}]*)</g;
const uiProperty = /\b(?:title|description|heading|introduction|question|answer|label|placeholder|body|copy|ctaLabel|alt)\s*[:=]\s*["']([^"'\n]{3,})["']/g;

for (const file of roots.flatMap(walk)) {
  const relative = path.relative(root, file).replaceAll("\\", "/");
  const lines = fs.readFileSync(file, "utf8").split(/\r?\n/);
  lines.forEach((line, index) => {
    const values = [...line.matchAll(jsxText), ...line.matchAll(uiProperty)]
      .map((match) => match[1]?.replace(/\s+/g, " ").trim())
      .filter((value): value is string => Boolean(value) && !/^[\d\W]+$/.test(value));
    for (const value of new Set(values)) candidates.push(`${relative}:${index + 1}\t${value}`);
  });
}

const header = [
  "# Localization untranslated-string candidates",
  "# Generated by scripts/localization-audit.ts",
  "# This is a review inventory, not an assertion that every candidate should be translated.",
  "# Dynamic database/user content, identifiers, legal copy, payment copy, and deferred phases intentionally remain unchanged.",
  "",
];
const output = path.join(root, "reports", "localization-untranslated.txt");
fs.mkdirSync(path.dirname(output), { recursive: true });
fs.writeFileSync(output, `${header.join("\n")}${candidates.join("\n")}\n`);
console.log(`Wrote ${candidates.length} untranslated-string candidates to ${output}.`);
