begin;

create temp table if not exists seed_workout_templates (
  name text not null,
  slug text not null,
  goal text,
  difficulty text,
  estimated_duration_minutes integer,
  equipment text[] not null,
  overview text,
  who_it_is_for text,
  warmup_guidance text,
  progression_guidance text,
  experience_level text,
  training_days_per_week integer,
  target_muscle_groups text[] not null,
  seo_title text,
  seo_description text
) on commit drop;

insert into seed_workout_templates (
  name,
  slug,
  goal,
  difficulty,
  estimated_duration_minutes,
  equipment,
  overview,
  who_it_is_for,
  warmup_guidance,
  progression_guidance,
  experience_level,
  training_days_per_week,
  target_muscle_groups,
  seo_title,
  seo_description
)
values
  (
    'Beginner Full Body Workout',
    'beginner-full-body-workout',
    'beginner',
    'beginner',
    50,
    array['dumbbell', 'bodyweight', 'machine']::text[],
    'A simple full-body workout that teaches the basic movement patterns without burying beginners in volume.',
    'Someone new to lifting who wants a clear first program with a little bit of everything.',
    'Start with 5 minutes of light cardio, then do one easy warm-up set before each main lift.',
    'When every set feels smooth at the top of the rep range, add a small amount of weight the next session.',
    'beginner',
    3,
    array['legs', 'chest', 'back', 'shoulders', 'core']::text[],
    'Beginner Full Body Workout: Free Workout Template for Logbook',
    'Beginner Full Body Workout is a beginner workout template focused on beginner with exercises, sets, reps, and rest guidance.'
  ),
  (
    'Beginner Weight Loss Workout',
    'beginner-weight-loss-workout',
    'weight-loss',
    'beginner',
    40,
    array['bodyweight', 'dumbbell']::text[],
    'A low-complexity circuit that keeps you moving while still building basic strength.',
    'A beginner who wants a sustainable starting point for fat loss instead of an extreme plan.',
    'Walk for 5 minutes and practice one slow rehearsal set of each movement before the circuit starts.',
    'Add a round, a few reps, or a small amount of load before you jump straight to much harder exercises.',
    'beginner',
    3,
    array['legs', 'chest', 'back', 'shoulders', 'core']::text[],
    'Beginner Weight Loss Workout: Free Workout Template for Logbook',
    'Beginner Weight Loss Workout is a beginner workout template focused on weight loss with exercises, sets, reps, and rest guidance.'
  ),
  (
    'Beginner Dumbbell Workout',
    'beginner-dumbbell-workout',
    'beginner',
    'beginner',
    45,
    array['dumbbell', 'bodyweight']::text[],
    'A full-body dumbbell session that works well in a home gym or a crowded commercial gym.',
    'Someone who only has dumbbells or wants to learn the basics before using barbells.',
    'Take one lighter warm-up set for the first lower-body and upper-body move.',
    'Own the full rep range first, then increase weight in the smallest jump available.',
    'beginner',
    3,
    array['legs', 'chest', 'back', 'shoulders', 'arms']::text[],
    'Beginner Dumbbell Workout: Free Workout Template for Logbook',
    'Beginner Dumbbell Workout is a beginner workout template focused on beginner with exercises, sets, reps, and rest guidance.'
  ),
  (
    'Beginner Gym Workout',
    'beginner-gym-workout',
    'beginner',
    'beginner',
    50,
    array['machine', 'cable', 'bodyweight']::text[],
    'A beginner-friendly gym session built around stable machines and simple cable patterns.',
    'Someone brand new to the gym floor who wants a little more support and stability.',
    'Use 5 minutes of easy cardio and one lighter warm-up set on the first two machines.',
    'Only move the pin up after you hit every prescribed rep without grinding.',
    'beginner',
    3,
    array['legs', 'chest', 'back', 'shoulders', 'core']::text[],
    'Beginner Gym Workout: Free Workout Template for Logbook',
    'Beginner Gym Workout is a beginner workout template focused on beginner with exercises, sets, reps, and rest guidance.'
  ),
  (
    'Beginner Home Workout',
    'beginner-home-workout',
    'beginner',
    'beginner',
    35,
    array['bodyweight']::text[],
    'A bodyweight-only starting plan you can run at home with very little setup.',
    'Someone who wants a realistic at-home plan before buying more equipment.',
    'Walk around for a few minutes, then do a slow practice round of the circuit.',
    'Add reps first. When that gets easy, shorten rest periods or add a fourth round.',
    'beginner',
    3,
    array['legs', 'chest', 'arms', 'core']::text[],
    'Beginner Home Workout: Free Workout Template for Logbook',
    'Beginner Home Workout is a beginner workout template focused on beginner with exercises, sets, reps, and rest guidance.'
  ),
  (
    'Push Day Workout',
    'push-day-workout',
    'muscle-building',
    'intermediate',
    65,
    array['barbell', 'dumbbell', 'cable']::text[],
    'A classic push day for chest, shoulders, and triceps with a balance of compound and accessory work.',
    'Lifters who already know the basics and want a clean upper-body push session.',
    'Warm up your shoulders and upper back, then climb in weight with 2 to 3 ramp-up sets on the first press.',
    'Drive progress through the first two presses first, then add reps or load on accessories as recovery allows.',
    'intermediate',
    5,
    array['chest', 'shoulders', 'arms']::text[],
    'Push Day Workout: Free Workout Template for Logbook',
    'Push Day Workout is a intermediate workout template focused on muscle building with exercises, sets, reps, and rest guidance.'
  ),
  (
    'Pull Day Workout',
    'pull-day-workout',
    'muscle-building',
    'intermediate',
    65,
    array['barbell', 'cable', 'bodyweight']::text[],
    'A pull day built around back thickness, back width, and direct arm work.',
    'Lifters who want a simple back and biceps session they can progress for months.',
    'Do a few shoulder circles, a couple sets of band or cable rows, and then ramp into the first rowing movement.',
    'Chase better form and load on the main row before making the accessory work more complicated.',
    'intermediate',
    5,
    array['back', 'arms']::text[],
    'Pull Day Workout: Free Workout Template for Logbook',
    'Pull Day Workout is a intermediate workout template focused on muscle building with exercises, sets, reps, and rest guidance.'
  ),
  (
    'Leg Day Workout',
    'leg-day-workout',
    'muscle-building',
    'intermediate',
    70,
    array['barbell', 'machine', 'bodyweight']::text[],
    'A leg day that covers squat strength, posterior-chain work, and enough accessory volume to grow.',
    'Someone who wants a balanced lower-body session instead of only squats and leg press.',
    'Warm up the hips and ankles, then build into the first squat pattern with 3 to 4 ramp-up sets.',
    'Treat the squat and hinge as the main drivers of progress, then use the accessories to add controlled volume.',
    'intermediate',
    5,
    array['legs', 'glutes']::text[],
    'Leg Day Workout: Free Workout Template for Logbook',
    'Leg Day Workout is a intermediate workout template focused on muscle building with exercises, sets, reps, and rest guidance.'
  ),
  (
    'Upper Body Workout',
    'upper-body-workout',
    'muscle-building',
    'intermediate',
    60,
    array['barbell', 'cable', 'dumbbell']::text[],
    'A balanced upper-body day built around pressing, rowing, pulling, and arm accessories.',
    'Lifters who want a straightforward upper session they can run once or twice per week.',
    'Prime the upper back and shoulders first, then take a few ramp-up sets on the main press.',
    'Progress the first press and row as a pair, then add small improvements on the rest of the session.',
    'intermediate',
    4,
    array['chest', 'back', 'shoulders', 'arms']::text[],
    'Upper Body Workout: Free Workout Template for Logbook',
    'Upper Body Workout is a intermediate workout template focused on muscle building with exercises, sets, reps, and rest guidance.'
  ),
  (
    'Lower Body Workout',
    'lower-body-workout',
    'muscle-building',
    'intermediate',
    65,
    array['barbell', 'dumbbell', 'machine']::text[],
    'A lower-body template that covers squat strength, single-leg work, and posterior-chain volume.',
    'Lifters who want a lower day that is productive without being overly complicated.',
    'Mobilize hips and ankles, then build into the first squat movement with several small jumps.',
    'Add weight slowly on the main squat pattern and use the accessories to own more reps before more load.',
    'intermediate',
    4,
    array['legs', 'glutes']::text[],
    'Lower Body Workout: Free Workout Template for Logbook',
    'Lower Body Workout is a intermediate workout template focused on muscle building with exercises, sets, reps, and rest guidance.'
  ),
  (
    '3-Day Full Body Split',
    '3-day-full-body-split',
    'muscle-building',
    'beginner',
    55,
    array['barbell', 'dumbbell', 'cable', 'bodyweight']::text[],
    'A three-day split that spreads total weekly work across three full-body sessions.',
    'Someone who can train three days per week and wants steady progress without body-part specialization yet.',
    'Use 5 minutes of easy cardio plus one to three ramp-up sets before the first compound lift on each day.',
    'Aim to improve one big lift and one accessory on each day before adding more overall volume.',
    'beginner',
    3,
    array['legs', 'chest', 'back', 'shoulders', 'arms']::text[],
    '3-Day Full Body Split: Free Workout Template for Logbook',
    '3-Day Full Body Split is a beginner workout template focused on muscle building with exercises, sets, reps, and rest guidance.'
  ),
  (
    '4-Day Upper Lower Split',
    '4-day-upper-lower-split',
    'muscle-building',
    'intermediate',
    60,
    array['barbell', 'dumbbell', 'cable', 'machine']::text[],
    'A simple four-day split that gives each half of the body two quality sessions each week.',
    'Someone beyond the beginner stage who wants structure without a five- or six-day schedule.',
    'Warm up separately for the first press or squat on each day, then take one lighter set before the next big lift.',
    'Rotate your focus between load on the first compounds and rep quality on the secondary work.',
    'intermediate',
    4,
    array['legs', 'chest', 'back', 'shoulders', 'arms']::text[],
    '4-Day Upper Lower Split: Free Workout Template for Logbook',
    '4-Day Upper Lower Split is a intermediate workout template focused on muscle building with exercises, sets, reps, and rest guidance.'
  ),
  (
    '5-Day Bodybuilding Split',
    '5-day-bodybuilding-split',
    'muscle-building',
    'intermediate',
    70,
    array['barbell', 'dumbbell', 'cable', 'machine']::text[],
    'A traditional five-day bodybuilding split for lifters who enjoy focusing on one or two regions per session.',
    'Someone who can recover from higher weekly volume and likes dedicated body-part days.',
    'Use targeted mobility and ramp-up sets for the first compound on each day.',
    'Keep the main compound stable from block to block and rotate smaller accessories as needed.',
    'intermediate',
    5,
    array['chest', 'back', 'legs', 'shoulders', 'arms']::text[],
    '5-Day Bodybuilding Split: Free Workout Template for Logbook',
    '5-Day Bodybuilding Split is a intermediate workout template focused on muscle building with exercises, sets, reps, and rest guidance.'
  ),
  (
    'Chest and Triceps Workout',
    'chest-and-triceps-workout',
    'muscle-building',
    'intermediate',
    60,
    array['barbell', 'dumbbell', 'cable']::text[],
    'A chest-focused session with enough triceps work to support pressing strength and arm size.',
    'Lifters who want to bias chest volume without turning the workout into random burnout work.',
    'Open the shoulders and upper back first, then use 2 to 3 ramp-up sets on the first bench pattern.',
    'Improve the first press over time, then use the cable and triceps work to build extra volume.',
    'intermediate',
    5,
    array['chest', 'arms']::text[],
    'Chest and Triceps Workout: Free Workout Template for Logbook',
    'Chest and Triceps Workout is a intermediate workout template focused on muscle building with exercises, sets, reps, and rest guidance.'
  ),
  (
    'Back and Biceps Workout',
    'back-and-biceps-workout',
    'muscle-building',
    'intermediate',
    60,
    array['barbell', 'cable', 'dumbbell']::text[],
    'A straightforward back and biceps workout with vertical pulls, rows, and direct arm work.',
    'Lifters who want a dedicated pull session with a little more direct biceps volume.',
    'Use easy rows and shoulder circles before you start ramping into the first heavy pull.',
    'Keep the first row or pulldown movement stable long enough to actually see strength move.',
    'intermediate',
    5,
    array['back', 'arms']::text[],
    'Back and Biceps Workout: Free Workout Template for Logbook',
    'Back and Biceps Workout is a intermediate workout template focused on muscle building with exercises, sets, reps, and rest guidance.'
  ),
  (
    'Shoulder Workout',
    'shoulder-workout',
    'muscle-building',
    'intermediate',
    55,
    array['barbell', 'dumbbell', 'cable']::text[],
    'A shoulder session built around pressing and higher-rep delt work.',
    'Lifters who want more direct shoulder work without adding too much unnecessary complexity.',
    'Warm up the rotator cuff, upper back, and thoracic spine before the main press.',
    'Push the main press over time and keep the lateral and rear-delt work strict.',
    'intermediate',
    5,
    array['shoulders', 'arms']::text[],
    'Shoulder Workout: Free Workout Template for Logbook',
    'Shoulder Workout is a intermediate workout template focused on muscle building with exercises, sets, reps, and rest guidance.'
  ),
  (
    'Arm Workout',
    'arm-workout',
    'muscle-building',
    'intermediate',
    45,
    array['ez-bar', 'dumbbell', 'cable', 'bodyweight']::text[],
    'A focused arm session with direct biceps and triceps volume you can recover from.',
    'Lifters who want a shorter accessory-focused session to bring up the arms.',
    'Warm up elbows and shoulders with a couple of very light cable or dumbbell sets.',
    'Progress slowly and stay honest with form so the target muscles keep doing the work.',
    'intermediate',
    5,
    array['arms']::text[],
    'Arm Workout: Free Workout Template for Logbook',
    'Arm Workout is a intermediate workout template focused on muscle building with exercises, sets, reps, and rest guidance.'
  ),
  (
    'Glute Workout',
    'glute-workout',
    'muscle-building',
    'intermediate',
    55,
    array['barbell', 'dumbbell', 'machine']::text[],
    'A glute-focused lower-body session that still keeps the rest of the lower body working.',
    'Someone who wants more direct glute emphasis without abandoning overall leg strength.',
    'Do a few glute bridges and bodyweight hinges before you start adding load.',
    'Drive the hip-dominant lifts first, then use the single-leg work and accessories for extra volume.',
    'intermediate',
    4,
    array['glutes', 'legs']::text[],
    'Glute Workout: Free Workout Template for Logbook',
    'Glute Workout is a intermediate workout template focused on muscle building with exercises, sets, reps, and rest guidance.'
  ),
  (
    'Core Workout',
    'core-workout',
    'muscle-building',
    'beginner',
    30,
    array['bodyweight', 'cable', 'other']::text[],
    'A direct core session built around control, trunk stiffness, and consistent tension.',
    'Anyone who wants a simple core-focused add-on without turning it into endless random ab work.',
    'Take a minute to breathe and brace before you start the first set.',
    'Progress by owning longer holds or cleaner reps before you chase harder variations.',
    'beginner',
    2,
    array['core']::text[],
    'Core Workout: Free Workout Template for Logbook',
    'Core Workout is a beginner workout template focused on muscle building with exercises, sets, reps, and rest guidance.'
  ),
  (
    '30-Minute Fat Loss Workout',
    '30-minute-fat-loss-workout',
    'weight-loss',
    'beginner',
    30,
    array['dumbbell', 'bodyweight']::text[],
    'A shorter full-body session designed to keep you moving and make consistency easier on busy days.',
    'Someone who wants a time-efficient workout instead of skipping the session altogether.',
    'Walk for a few minutes, then do one lighter round before the work sets start.',
    'Add reps or reduce rest before you add much more load.',
    'beginner',
    3,
    array['legs', 'chest', 'back', 'core']::text[],
    '30-Minute Fat Loss Workout: Free Workout Template for Logbook',
    '30-Minute Fat Loss Workout is a beginner workout template focused on weight loss with exercises, sets, reps, and rest guidance.'
  ),
  (
    'Walking and Strength Workout',
    'walking-and-strength-workout',
    'weight-loss',
    'beginner',
    45,
    array['dumbbell', 'bodyweight', 'other']::text[],
    'A lighter strength day built to pair well with a daily walking routine.',
    'Someone using walking as their main activity base and lifting to keep strength moving forward.',
    'Use a few minutes of easy walking before the first strength exercise, then save the rest of the walk for the end.',
    'Improve the strength work slowly and increase walking time only when recovery still feels good.',
    'beginner',
    3,
    array['legs', 'chest', 'back', 'core']::text[],
    'Walking and Strength Workout: Free Workout Template for Logbook',
    'Walking and Strength Workout is a beginner workout template focused on weight loss with exercises, sets, reps, and rest guidance.'
  ),
  (
    'Low-Impact Workout',
    'low-impact-workout',
    'beginner',
    'beginner',
    35,
    array['bodyweight', 'dumbbell', 'machine']::text[],
    'A gentle full-body workout that stays lower impact while still training the main muscle groups.',
    'Someone easing back into training, managing joint irritation, or wanting a lower-impact option.',
    'Move through a gentle range of motion and keep the first set of each move very easy.',
    'Add reps or another round first. Do not rush to turn a low-impact session into a max-effort one.',
    'beginner',
    3,
    array['legs', 'chest', 'back', 'core']::text[],
    'Low-Impact Workout: Free Workout Template for Logbook',
    'Low-Impact Workout is a beginner workout template focused on beginner with exercises, sets, reps, and rest guidance.'
  ),
  (
    'Hotel Gym Workout',
    'hotel-gym-workout',
    'beginner',
    'beginner',
    40,
    array['dumbbell', 'bodyweight']::text[],
    'A simple travel workout built around the dumbbells and bench you can usually find in a hotel gym.',
    'Someone traveling who wants to keep the training habit alive without chasing a perfect setup.',
    'Use a few minutes of walking and one easy set of each first movement.',
    'Keep the goal simple: do the work well and stay consistent while traveling.',
    'beginner',
    3,
    array['legs', 'chest', 'back', 'shoulders', 'core']::text[],
    'Hotel Gym Workout: Free Workout Template for Logbook',
    'Hotel Gym Workout is a beginner workout template focused on beginner with exercises, sets, reps, and rest guidance.'
  ),
  (
    'Busy Schedule 3-Day Workout',
    'busy-schedule-3-day-workout',
    'beginner',
    'beginner',
    40,
    array['barbell', 'dumbbell', 'bodyweight']::text[],
    'A three-day plan for people who need productive sessions without long training windows.',
    'A busy adult who wants to stay consistent with three manageable lifting days each week.',
    'Keep warm-ups short but intentional with a few easy ramp-up sets for the first lift.',
    'If life gets hectic, focus on the first three movements and consider the rest a bonus.',
    'beginner',
    3,
    array['legs', 'chest', 'back', 'shoulders']::text[],
    'Busy Schedule 3-Day Workout: Free Workout Template for Logbook',
    'Busy Schedule 3-Day Workout is a beginner workout template focused on beginner with exercises, sets, reps, and rest guidance.'
  ),
  (
    'Beginner Strength Program',
    'beginner-strength-program',
    'strength',
    'beginner',
    60,
    array['barbell', 'bodyweight']::text[],
    'A simple strength-first plan that keeps the exercise menu small enough to progress consistently.',
    'Someone who wants to learn barbell basics and make steady progress on the main lifts.',
    'Use multiple small jumps in load and keep the warm-up reps crisp before your work sets begin.',
    'Add small amounts of weight only when the prescribed reps are still clean and repeatable.',
    'beginner',
    3,
    array['legs', 'chest', 'back', 'shoulders']::text[],
    'Beginner Strength Program: Free Workout Template for Logbook',
    'Beginner Strength Program is a beginner workout template focused on strength with exercises, sets, reps, and rest guidance.'
  ),
  (
    'Powerlifting Beginner Program',
    'powerlifting-beginner-program',
    'strength',
    'beginner',
    70,
    array['barbell', 'bodyweight']::text[],
    'A beginner-friendly powerlifting structure built around the squat, bench press, and deadlift.',
    'Someone interested in strength sports who wants a clear first step without overly advanced programming.',
    'Treat the first three compound lifts seriously and take enough warm-up sets to feel sharp before work sets.',
    'Think long term. Small jumps and clean technique matter more than testing maxes too early.',
    'beginner',
    3,
    array['legs', 'chest', 'back', 'shoulders']::text[],
    'Powerlifting Beginner Program: Free Workout Template for Logbook',
    'Powerlifting Beginner Program is a beginner workout template focused on strength with exercises, sets, reps, and rest guidance.'
  ),
  (
    'Squat-Focused Workout',
    'squat-focused-workout',
    'strength',
    'intermediate',
    65,
    array['barbell', 'machine']::text[],
    'A lower-body workout that biases squat strength while still supporting long-term lower-body development.',
    'Someone who wants extra squat practice without turning the whole week into pure fatigue.',
    'Spend time opening the ankles and hips, then ramp up to your work sets gradually.',
    'Keep the first squat pattern as the main driver and let the rest of the day support it.',
    'intermediate',
    4,
    array['legs', 'glutes']::text[],
    'Squat-Focused Workout: Free Workout Template for Logbook',
    'Squat-Focused Workout is a intermediate workout template focused on strength with exercises, sets, reps, and rest guidance.'
  ),
  (
    'Bench Press-Focused Workout',
    'bench-press-focused-workout',
    'strength',
    'intermediate',
    60,
    array['barbell', 'cable', 'dumbbell']::text[],
    'An upper-body session designed to put the bench press first while still keeping shoulders and triceps moving forward.',
    'Someone trying to improve bench strength without losing chest and triceps size work.',
    'Use upper-back activation and several bench ramp-up sets before the work sets begin.',
    'Keep the first bench pattern consistent long enough to measure actual progress instead of hopping around.',
    'intermediate',
    4,
    array['chest', 'arms', 'shoulders']::text[],
    'Bench Press-Focused Workout: Free Workout Template for Logbook',
    'Bench Press-Focused Workout is a intermediate workout template focused on strength with exercises, sets, reps, and rest guidance.'
  ),
  (
    'Deadlift-Focused Workout',
    'deadlift-focused-workout',
    'strength',
    'intermediate',
    65,
    array['barbell', 'cable', 'machine']::text[],
    'A posterior-chain-heavy day built to support better deadlift performance without overcomplicating the session.',
    'Someone who wants extra deadlift attention while keeping the back and hamstrings strong enough to support it.',
    'Warm up the hinge pattern gradually and avoid jumping straight to heavy pulls cold.',
    'Let the deadlift lead the day and keep the accessory work heavy enough to matter but clean enough to recover from.',
    'intermediate',
    4,
    array['back', 'legs', 'glutes']::text[],
    'Deadlift-Focused Workout: Free Workout Template for Logbook',
    'Deadlift-Focused Workout is a intermediate workout template focused on strength with exercises, sets, reps, and rest guidance.'
  ),
  (
    'Strength and Hypertrophy Workout',
    'strength-and-hypertrophy-workout',
    'strength',
    'intermediate',
    65,
    array['barbell', 'dumbbell', 'cable', 'machine']::text[],
    'A mixed approach that pairs lower-rep compound work with higher-rep accessories in the same week.',
    'Someone who wants to keep getting stronger while still training for size and shape.',
    'Warm up the first compound thoroughly, then keep the accessory warm-up shorter and simpler.',
    'Use load progression on the first lift of each day and rep progression on the rest of the session.',
    'intermediate',
    4,
    array['legs', 'chest', 'back', 'shoulders', 'arms']::text[],
    'Strength and Hypertrophy Workout: Free Workout Template for Logbook',
    'Strength and Hypertrophy Workout is a intermediate workout template focused on strength with exercises, sets, reps, and rest guidance.'
  );

insert into public.workout_templates (
  user_id,
  name,
  slug,
  goal,
  difficulty,
  estimated_duration_minutes,
  equipment,
  overview,
  who_it_is_for,
  warmup_guidance,
  progression_guidance,
  experience_level,
  training_days_per_week,
  target_muscle_groups,
  seo_title,
  seo_description,
  is_public
)
select
  null,
  name,
  slug,
  goal,
  difficulty,
  estimated_duration_minutes,
  equipment,
  overview,
  who_it_is_for,
  warmup_guidance,
  progression_guidance,
  experience_level,
  training_days_per_week,
  target_muscle_groups,
  seo_title,
  seo_description,
  true
from seed_workout_templates
on conflict (slug) do update
set
  user_id = excluded.user_id,
  name = excluded.name,
  goal = excluded.goal,
  difficulty = excluded.difficulty,
  estimated_duration_minutes = excluded.estimated_duration_minutes,
  equipment = excluded.equipment,
  overview = excluded.overview,
  who_it_is_for = excluded.who_it_is_for,
  warmup_guidance = excluded.warmup_guidance,
  progression_guidance = excluded.progression_guidance,
  experience_level = excluded.experience_level,
  training_days_per_week = excluded.training_days_per_week,
  target_muscle_groups = excluded.target_muscle_groups,
  seo_title = excluded.seo_title,
  seo_description = excluded.seo_description,
  is_public = true,
  updated_at = timezone('utc', now());

delete from public.workout_template_exercises
where template_id in (
  select id
  from public.workout_templates
  where slug in (select slug from seed_workout_templates)
);

create temp table if not exists seed_workout_template_exercises (
  workout_template_slug text not null,
  exercise_slug text not null,
  day_label text,
  section text,
  sort_order integer not null,
  sets text,
  reps text,
  rest_seconds integer,
  notes text
) on commit drop;

insert into seed_workout_template_exercises (
  workout_template_slug,
  exercise_slug,
  day_label,
  section,
  sort_order,
  sets,
  reps,
  rest_seconds,
  notes
)
values
  (
    'beginner-full-body-workout',
    'goblet-squat',
    'Main Session',
    'Main work',
    1,
    '3',
    '8-10',
    90,
    'Use a controlled descent and pause briefly at the bottom.'
  ),
  (
    'beginner-full-body-workout',
    'dumbbell-bench-press',
    'Main Session',
    'Main work',
    2,
    '3',
    '8-10',
    90,
    'Keep your feet planted and press through the full range.'
  ),
  (
    'beginner-full-body-workout',
    'bodyweight-mid-row',
    'Main Session',
    'Main work',
    3,
    '3',
    '8-12',
    90,
    'Adjust the bar height so every rep stays clean.'
  ),
  (
    'beginner-full-body-workout',
    'dumbbell-shoulder-press',
    'Main Session',
    'Accessories',
    4,
    '2-3',
    '10-12',
    75,
    'Stop each rep before your lower back overextends.'
  ),
  (
    'beginner-full-body-workout',
    'romanian-deadlift',
    'Main Session',
    'Accessories',
    5,
    '2-3',
    '8-10',
    90,
    'Keep the bar or dumbbells close to your legs.'
  ),
  (
    'beginner-full-body-workout',
    'plank',
    'Main Session',
    'Core',
    6,
    '3',
    '20-40 sec',
    45,
    'Brace hard and keep your ribs stacked over your hips.'
  ),
  (
    'beginner-weight-loss-workout',
    'bodyweight-squat',
    'Circuit',
    'Circuit A',
    1,
    '3',
    '12-15',
    30,
    'Move at a steady pace and stay a few reps away from failure.'
  ),
  (
    'beginner-weight-loss-workout',
    'pushups',
    'Circuit',
    'Circuit A',
    2,
    '3',
    '6-12',
    30,
    'Elevate your hands if needed so you can keep good form.'
  ),
  (
    'beginner-weight-loss-workout',
    'bent-over-two-dumbbell-row',
    'Circuit',
    'Circuit A',
    3,
    '3',
    '10-12',
    30,
    'Squeeze your upper back at the top of each rep.'
  ),
  (
    'beginner-weight-loss-workout',
    'dumbbell-lunges',
    'Circuit',
    'Circuit B',
    4,
    '2-3',
    '10 each side',
    45,
    'Use a stride length that lets you stay balanced.'
  ),
  (
    'beginner-weight-loss-workout',
    'dumbbell-shoulder-press',
    'Circuit',
    'Circuit B',
    5,
    '2-3',
    '10-12',
    45,
    'Keep the motion smooth and stop before your back arches.'
  ),
  (
    'beginner-weight-loss-workout',
    '3-4-sit-up',
    'Circuit',
    'Core',
    6,
    '2-3',
    '12-15',
    30,
    'Focus on control instead of speed.'
  ),
  (
    'beginner-dumbbell-workout',
    'dumbbell-squat',
    'Main Session',
    'Main work',
    1,
    '3',
    '10-12',
    75,
    'Use a heel stance that lets you keep the chest tall.'
  ),
  (
    'beginner-dumbbell-workout',
    'dumbbell-bench-press',
    'Main Session',
    'Main work',
    2,
    '3',
    '8-10',
    90,
    'Lower with control and keep both dumbbells even.'
  ),
  (
    'beginner-dumbbell-workout',
    'bent-over-two-dumbbell-row',
    'Main Session',
    'Main work',
    3,
    '3',
    '10-12',
    75,
    'Pause at the top to feel the upper back work.'
  ),
  (
    'beginner-dumbbell-workout',
    'dumbbell-shoulder-press',
    'Main Session',
    'Accessories',
    4,
    '3',
    '8-10',
    75,
    'Press straight up instead of forward.'
  ),
  (
    'beginner-dumbbell-workout',
    'dumbbell-bicep-curl',
    'Main Session',
    'Accessories',
    5,
    '2-3',
    '10-12',
    45,
    'Keep the elbows from drifting forward.'
  ),
  (
    'beginner-dumbbell-workout',
    'dumbbell-one-arm-triceps-extension',
    'Main Session',
    'Accessories',
    6,
    '2-3',
    '10-12 each side',
    45,
    'Use a weight you can control overhead.'
  ),
  (
    'beginner-gym-workout',
    'leg-press',
    'Main Session',
    'Main work',
    1,
    '3',
    '10-12',
    90,
    'Lower as far as you can while keeping your low back supported.'
  ),
  (
    'beginner-gym-workout',
    'cable-chest-press',
    'Main Session',
    'Main work',
    2,
    '3',
    '10-12',
    75,
    'Keep the shoulders down and finish with a soft bend in the elbows.'
  ),
  (
    'beginner-gym-workout',
    'wide-grip-lat-pulldown',
    'Main Session',
    'Main work',
    3,
    '3',
    '8-12',
    75,
    'Pull to the upper chest instead of behind the neck.'
  ),
  (
    'beginner-gym-workout',
    'seated-cable-shoulder-press',
    'Main Session',
    'Accessories',
    4,
    '2-3',
    '10-12',
    75,
    'Stay stacked and avoid leaning back.'
  ),
  (
    'beginner-gym-workout',
    'seated-cable-rows',
    'Main Session',
    'Accessories',
    5,
    '2-3',
    '10-12',
    75,
    'Drive the elbows back without shrugging up.'
  ),
  (
    'beginner-gym-workout',
    'ab-crunch-machine',
    'Main Session',
    'Core',
    6,
    '2-3',
    '12-15',
    45,
    'Move slowly and let the abs do the work.'
  ),
  (
    'beginner-home-workout',
    'bodyweight-squat',
    'Circuit',
    'Circuit A',
    1,
    '3',
    '12-20',
    30,
    'Keep the pace steady and stay upright.'
  ),
  (
    'beginner-home-workout',
    'pushups',
    'Circuit',
    'Circuit A',
    2,
    '3',
    '6-15',
    30,
    'Use an incline if you need a cleaner version.'
  ),
  (
    'beginner-home-workout',
    'bodyweight-walking-lunge',
    'Circuit',
    'Circuit A',
    3,
    '3',
    '10 each side',
    30,
    'Take controlled steps and stay balanced.'
  ),
  (
    'beginner-home-workout',
    'bench-dips',
    'Circuit',
    'Circuit B',
    4,
    '2-3',
    '8-12',
    45,
    'Keep the shoulders comfortable and do not drop too deep.'
  ),
  (
    'beginner-home-workout',
    '3-4-sit-up',
    'Circuit',
    'Circuit B',
    5,
    '2-3',
    '12-15',
    30,
    'Use a smooth rhythm instead of jerking upward.'
  ),
  (
    'beginner-home-workout',
    'plank',
    'Circuit',
    'Circuit B',
    6,
    '2-3',
    '20-40 sec',
    30,
    'Think ribs down and glutes tight.'
  ),
  (
    'push-day-workout',
    'barbell-bench-press-medium-grip',
    'Push',
    'Primary presses',
    1,
    '4',
    '5-8',
    150,
    'Use the same setup every set so bar path stays repeatable.'
  ),
  (
    'push-day-workout',
    'barbell-incline-bench-press-medium-grip',
    'Push',
    'Primary presses',
    2,
    '3-4',
    '6-10',
    120,
    'Drive the upper chest without turning it into a shoulder press.'
  ),
  (
    'push-day-workout',
    'dumbbell-shoulder-press',
    'Push',
    'Shoulders',
    3,
    '3',
    '8-10',
    90,
    'Stay stacked and avoid leaning back.'
  ),
  (
    'push-day-workout',
    'side-lateral-raise',
    'Push',
    'Shoulders',
    4,
    '3',
    '12-15',
    45,
    'Lift with control and avoid swinging the torso.'
  ),
  (
    'push-day-workout',
    'close-grip-barbell-bench-press',
    'Push',
    'Triceps',
    5,
    '3',
    '6-8',
    120,
    'Keep the elbows tucked and control the bottom position.'
  ),
  (
    'push-day-workout',
    'reverse-grip-triceps-pushdown',
    'Push',
    'Triceps',
    6,
    '3',
    '10-15',
    45,
    'Focus on full elbow lockout without rolling the shoulders forward.'
  ),
  (
    'pull-day-workout',
    'bent-over-barbell-row',
    'Pull',
    'Primary pulls',
    1,
    '4',
    '6-8',
    150,
    'Brace hard and keep the torso angle consistent.'
  ),
  (
    'pull-day-workout',
    'wide-grip-lat-pulldown',
    'Pull',
    'Primary pulls',
    2,
    '3-4',
    '8-10',
    90,
    'Drive the elbows down instead of yanking with the hands.'
  ),
  (
    'pull-day-workout',
    'seated-cable-rows',
    'Pull',
    'Upper back',
    3,
    '3',
    '8-12',
    90,
    'Pause briefly against the torso.'
  ),
  (
    'pull-day-workout',
    'straight-arm-pulldown',
    'Pull',
    'Upper back',
    4,
    '3',
    '10-15',
    45,
    'Keep a small bend in the elbows and move from the shoulders.'
  ),
  (
    'pull-day-workout',
    'barbell-curl',
    'Pull',
    'Biceps',
    5,
    '3',
    '8-10',
    60,
    'Do not let the lower back create the rep.'
  ),
  (
    'pull-day-workout',
    'alternate-hammer-curl',
    'Pull',
    'Biceps',
    6,
    '3',
    '10-12',
    45,
    'Let the arms fully extend before the next rep.'
  ),
  (
    'leg-day-workout',
    'barbell-squat',
    'Legs',
    'Primary lower body',
    1,
    '4',
    '5-8',
    180,
    'Keep the same stance and brace before every rep.'
  ),
  (
    'leg-day-workout',
    'leg-press',
    'Legs',
    'Primary lower body',
    2,
    '3',
    '10-12',
    120,
    'Use a depth you can control without the hips rolling.'
  ),
  (
    'leg-day-workout',
    'romanian-deadlift',
    'Legs',
    'Posterior chain',
    3,
    '3',
    '8-10',
    120,
    'Think hips back and keep tension through the hamstrings.'
  ),
  (
    'leg-day-workout',
    'leg-extensions',
    'Legs',
    'Accessories',
    4,
    '3',
    '12-15',
    60,
    'Pause the lockout instead of bouncing through it.'
  ),
  (
    'leg-day-workout',
    'lying-leg-curls',
    'Legs',
    'Accessories',
    5,
    '3',
    '10-15',
    60,
    'Stay controlled on the lowering phase.'
  ),
  (
    'leg-day-workout',
    'calf-press-on-the-leg-press-machine',
    'Legs',
    'Finishers',
    6,
    '3',
    '12-20',
    45,
    'Use a full stretch and squeeze each rep.'
  ),
  (
    'upper-body-workout',
    'barbell-bench-press-medium-grip',
    'Upper',
    'Primary lifts',
    1,
    '4',
    '5-8',
    150,
    'Use a setup you can repeat every week.'
  ),
  (
    'upper-body-workout',
    'bent-over-barbell-row',
    'Upper',
    'Primary lifts',
    2,
    '4',
    '6-8',
    150,
    'Own the torso angle and row to the same point each rep.'
  ),
  (
    'upper-body-workout',
    'wide-grip-lat-pulldown',
    'Upper',
    'Secondary work',
    3,
    '3',
    '8-12',
    90,
    'Think elbows down and chest tall.'
  ),
  (
    'upper-body-workout',
    'dumbbell-shoulder-press',
    'Upper',
    'Secondary work',
    4,
    '3',
    '8-10',
    75,
    'Keep the dumbbells stacked over the elbows.'
  ),
  (
    'upper-body-workout',
    'ez-bar-curl',
    'Upper',
    'Arms',
    5,
    '3',
    '10-12',
    45,
    'Use the full range instead of half reps.'
  ),
  (
    'upper-body-workout',
    'reverse-grip-triceps-pushdown',
    'Upper',
    'Arms',
    6,
    '3',
    '10-12',
    45,
    'Keep the upper arm quiet and lock out hard.'
  ),
  (
    'lower-body-workout',
    'front-barbell-squat',
    'Lower',
    'Primary lower body',
    1,
    '4',
    '4-6',
    180,
    'Drive the elbows up and stay tall out of the hole.'
  ),
  (
    'lower-body-workout',
    'romanian-deadlift',
    'Lower',
    'Primary lower body',
    2,
    '3',
    '6-8',
    150,
    'Do not lose lat tension on the way down.'
  ),
  (
    'lower-body-workout',
    'dumbbell-lunges',
    'Lower',
    'Single-leg',
    3,
    '3',
    '8-10 each side',
    75,
    'Use a steady step and finish balanced.'
  ),
  (
    'lower-body-workout',
    'leg-press',
    'Lower',
    'Accessories',
    4,
    '3',
    '10-12',
    90,
    'Push through the full foot and control the descent.'
  ),
  (
    'lower-body-workout',
    'lying-leg-curls',
    'Lower',
    'Accessories',
    5,
    '3',
    '10-15',
    60,
    'Keep the hips pinned down.'
  ),
  (
    'lower-body-workout',
    'calf-press-on-the-leg-press-machine',
    'Lower',
    'Finishers',
    6,
    '3',
    '12-20',
    45,
    'Pause in the stretched position briefly.'
  ),
  (
    '3-day-full-body-split',
    'barbell-squat',
    'Day 1',
    'Main work',
    1,
    '4',
    '5-6',
    150,
    'Stay a rep or two shy of failure.'
  ),
  (
    '3-day-full-body-split',
    'barbell-bench-press-medium-grip',
    'Day 1',
    'Main work',
    2,
    '4',
    '5-8',
    150,
    'Repeat the same bar path every set.'
  ),
  (
    '3-day-full-body-split',
    'wide-grip-lat-pulldown',
    'Day 1',
    'Main work',
    3,
    '3',
    '8-10',
    75,
    'Control the return.'
  ),
  (
    '3-day-full-body-split',
    'romanian-deadlift',
    'Day 2',
    'Main work',
    4,
    '4',
    '6-8',
    150,
    'Keep tension the whole set.'
  ),
  (
    '3-day-full-body-split',
    'dumbbell-shoulder-press',
    'Day 2',
    'Main work',
    5,
    '3',
    '8-10',
    75,
    'Press from a stable torso.'
  ),
  (
    '3-day-full-body-split',
    'seated-cable-rows',
    'Day 2',
    'Main work',
    6,
    '3',
    '8-12',
    75,
    'Use a full squeeze.'
  ),
  (
    '3-day-full-body-split',
    'leg-press',
    'Day 3',
    'Main work',
    7,
    '3',
    '10-12',
    90,
    'Stay smooth and controlled.'
  ),
  (
    '3-day-full-body-split',
    'barbell-incline-bench-press-medium-grip',
    'Day 3',
    'Main work',
    8,
    '3',
    '8-10',
    90,
    'Drive through the upper chest.'
  ),
  (
    '3-day-full-body-split',
    'bent-over-barbell-row',
    'Day 3',
    'Main work',
    9,
    '3',
    '8-10',
    90,
    'Do not let the torso drift.'
  ),
  (
    '4-day-upper-lower-split',
    'barbell-bench-press-medium-grip',
    'Upper A',
    'Primary lifts',
    1,
    '4',
    '5-8',
    150,
    'Main press for the week.'
  ),
  (
    '4-day-upper-lower-split',
    'bent-over-barbell-row',
    'Upper A',
    'Primary lifts',
    2,
    '4',
    '6-8',
    150,
    'Row hard but stay braced.'
  ),
  (
    '4-day-upper-lower-split',
    'dumbbell-shoulder-press',
    'Upper A',
    'Accessories',
    3,
    '3',
    '8-10',
    75,
    'Stack the dumbbells over the elbows.'
  ),
  (
    '4-day-upper-lower-split',
    'barbell-squat',
    'Lower A',
    'Primary lifts',
    4,
    '4',
    '5-6',
    180,
    'Treat this as the heavy squat day.'
  ),
  (
    '4-day-upper-lower-split',
    'romanian-deadlift',
    'Lower A',
    'Primary lifts',
    5,
    '3',
    '6-8',
    150,
    'Use the hamstrings, not momentum.'
  ),
  (
    '4-day-upper-lower-split',
    'leg-extensions',
    'Lower A',
    'Accessories',
    6,
    '3',
    '12-15',
    60,
    'Own the lockout.'
  ),
  (
    '4-day-upper-lower-split',
    'barbell-incline-bench-press-medium-grip',
    'Upper B',
    'Primary lifts',
    7,
    '4',
    '6-10',
    120,
    'Slightly higher-rep pressing day.'
  ),
  (
    '4-day-upper-lower-split',
    'wide-grip-lat-pulldown',
    'Upper B',
    'Primary lifts',
    8,
    '4',
    '8-10',
    90,
    'Move cleanly through the full range.'
  ),
  (
    '4-day-upper-lower-split',
    'ez-bar-curl',
    'Upper B',
    'Accessories',
    9,
    '3',
    '10-12',
    45,
    'Control both sides evenly.'
  ),
  (
    '4-day-upper-lower-split',
    'front-barbell-squat',
    'Lower B',
    'Primary lifts',
    10,
    '3',
    '4-6',
    180,
    'Stay tall and drive up.'
  ),
  (
    '4-day-upper-lower-split',
    'leg-press',
    'Lower B',
    'Primary lifts',
    11,
    '3',
    '10-12',
    90,
    'Control the descent.'
  ),
  (
    '4-day-upper-lower-split',
    'lying-leg-curls',
    'Lower B',
    'Accessories',
    12,
    '3',
    '10-15',
    60,
    'Keep the motion smooth.'
  ),
  (
    '5-day-bodybuilding-split',
    'barbell-bench-press-medium-grip',
    'Chest',
    'Primary work',
    1,
    '4',
    '5-8',
    150,
    'Primary chest driver.'
  ),
  (
    '5-day-bodybuilding-split',
    'flat-bench-cable-flyes',
    'Chest',
    'Accessories',
    2,
    '3',
    '12-15',
    45,
    'Stretch and squeeze.'
  ),
  (
    '5-day-bodybuilding-split',
    'bent-over-barbell-row',
    'Back',
    'Primary work',
    3,
    '4',
    '6-8',
    150,
    'Back thickness focus.'
  ),
  (
    '5-day-bodybuilding-split',
    'wide-grip-lat-pulldown',
    'Back',
    'Accessories',
    4,
    '3',
    '8-12',
    75,
    'Back width focus.'
  ),
  (
    '5-day-bodybuilding-split',
    'barbell-squat',
    'Legs',
    'Primary work',
    5,
    '4',
    '5-8',
    180,
    'Main lower-body lift.'
  ),
  (
    '5-day-bodybuilding-split',
    'leg-press',
    'Legs',
    'Accessories',
    6,
    '3',
    '10-12',
    90,
    'Controlled depth.'
  ),
  (
    '5-day-bodybuilding-split',
    'barbell-shoulder-press',
    'Shoulders',
    'Primary work',
    7,
    '4',
    '6-8',
    120,
    'Drive straight up and stay braced.'
  ),
  (
    '5-day-bodybuilding-split',
    'side-lateral-raise',
    'Shoulders',
    'Accessories',
    8,
    '3',
    '12-15',
    45,
    'Stay strict.'
  ),
  (
    '5-day-bodybuilding-split',
    'ez-bar-curl',
    'Arms',
    'Primary work',
    9,
    '3',
    '8-10',
    45,
    'Use a steady tempo.'
  ),
  (
    '5-day-bodybuilding-split',
    'reverse-grip-triceps-pushdown',
    'Arms',
    'Primary work',
    10,
    '3',
    '10-12',
    45,
    'Chase full elbow extension.'
  ),
  (
    'chest-and-triceps-workout',
    'barbell-bench-press-medium-grip',
    'Chest and Triceps',
    'Chest',
    1,
    '4',
    '5-8',
    150,
    'Lead the day with your most stable press.'
  ),
  (
    'chest-and-triceps-workout',
    'barbell-incline-bench-press-medium-grip',
    'Chest and Triceps',
    'Chest',
    2,
    '3',
    '6-10',
    120,
    'Slight incline and smooth reps.'
  ),
  (
    'chest-and-triceps-workout',
    'flat-bench-cable-flyes',
    'Chest and Triceps',
    'Chest',
    3,
    '3',
    '12-15',
    45,
    'Stretch under control.'
  ),
  (
    'chest-and-triceps-workout',
    'close-grip-barbell-bench-press',
    'Chest and Triceps',
    'Triceps',
    4,
    '3',
    '6-8',
    120,
    'Use a strong setup and tuck the elbows.'
  ),
  (
    'chest-and-triceps-workout',
    'reverse-grip-triceps-pushdown',
    'Chest and Triceps',
    'Triceps',
    5,
    '3',
    '10-12',
    45,
    'Finish every rep fully.'
  ),
  (
    'chest-and-triceps-workout',
    'cable-rope-overhead-triceps-extension',
    'Chest and Triceps',
    'Triceps',
    6,
    '2-3',
    '12-15',
    45,
    'Let the long head stretch comfortably.'
  ),
  (
    'back-and-biceps-workout',
    'bent-over-barbell-row',
    'Back and Biceps',
    'Back',
    1,
    '4',
    '6-8',
    150,
    'Lead with the elbows and stay braced.'
  ),
  (
    'back-and-biceps-workout',
    'wide-grip-lat-pulldown',
    'Back and Biceps',
    'Back',
    2,
    '3-4',
    '8-10',
    90,
    'Avoid jerking the weight.'
  ),
  (
    'back-and-biceps-workout',
    'seated-cable-rows',
    'Back and Biceps',
    'Back',
    3,
    '3',
    '8-12',
    90,
    'Own the squeeze.'
  ),
  (
    'back-and-biceps-workout',
    'straight-arm-pulldown',
    'Back and Biceps',
    'Back',
    4,
    '3',
    '12-15',
    45,
    'Let the lats finish the rep.'
  ),
  (
    'back-and-biceps-workout',
    'barbell-curl',
    'Back and Biceps',
    'Biceps',
    5,
    '3',
    '8-10',
    60,
    'Keep the torso quiet.'
  ),
  (
    'back-and-biceps-workout',
    'alternate-hammer-curl',
    'Back and Biceps',
    'Biceps',
    6,
    '3',
    '10-12',
    45,
    'Control the lowering phase.'
  ),
  (
    'shoulder-workout',
    'barbell-shoulder-press',
    'Shoulders',
    'Presses',
    1,
    '4',
    '5-8',
    150,
    'Brace hard and press in a straight line.'
  ),
  (
    'shoulder-workout',
    'arnold-dumbbell-press',
    'Shoulders',
    'Presses',
    2,
    '3',
    '8-10',
    90,
    'Use a weight you can control through the full path.'
  ),
  (
    'shoulder-workout',
    'side-lateral-raise',
    'Shoulders',
    'Side delts',
    3,
    '4',
    '12-15',
    45,
    'Keep tension on the delts, not momentum.'
  ),
  (
    'shoulder-workout',
    'bent-over-dumbbell-rear-delt-raise-with-head-on-bench',
    'Shoulders',
    'Rear delts',
    4,
    '3',
    '12-15',
    45,
    'Keep the neck relaxed and move from the shoulders.'
  ),
  (
    'shoulder-workout',
    'barbell-shrug',
    'Shoulders',
    'Upper traps',
    5,
    '3',
    '10-12',
    60,
    'Lift straight up and pause briefly.'
  ),
  (
    'arm-workout',
    'close-grip-ez-bar-curl',
    'Arms',
    'Biceps',
    1,
    '3',
    '8-10',
    60,
    'Stay strict and keep the elbows pinned.'
  ),
  (
    'arm-workout',
    'alternate-hammer-curl',
    'Arms',
    'Biceps',
    2,
    '3',
    '10-12',
    45,
    'Move one arm at a time with full control.'
  ),
  (
    'arm-workout',
    'concentration-curls',
    'Arms',
    'Biceps',
    3,
    '2-3',
    '10-12',
    45,
    'Squeeze hard at the top.'
  ),
  (
    'arm-workout',
    'reverse-grip-triceps-pushdown',
    'Arms',
    'Triceps',
    4,
    '3',
    '10-12',
    45,
    'Keep the upper arm from drifting.'
  ),
  (
    'arm-workout',
    'cable-rope-overhead-triceps-extension',
    'Arms',
    'Triceps',
    5,
    '3',
    '12-15',
    45,
    'Use a full stretch that still feels stable.'
  ),
  (
    'arm-workout',
    'dips-triceps-version',
    'Arms',
    'Triceps',
    6,
    '2-3',
    '6-10',
    75,
    'Stay upright to bias the triceps.'
  ),
  (
    'glute-workout',
    'barbell-hip-thrust',
    'Glutes',
    'Primary work',
    1,
    '4',
    '6-10',
    120,
    'Pause hard at the top and avoid overextending the back.'
  ),
  (
    'glute-workout',
    'romanian-deadlift',
    'Glutes',
    'Primary work',
    2,
    '3',
    '8-10',
    120,
    'Feel the stretch through the glutes and hamstrings.'
  ),
  (
    'glute-workout',
    'barbell-walking-lunge',
    'Glutes',
    'Single-leg',
    3,
    '3',
    '8-10 each side',
    75,
    'Take long, controlled steps.'
  ),
  (
    'glute-workout',
    'leg-press',
    'Glutes',
    'Accessories',
    4,
    '3',
    '10-12',
    90,
    'Use a foot position that lets the hips stay comfortable.'
  ),
  (
    'glute-workout',
    'pull-through',
    'Glutes',
    'Accessories',
    5,
    '3',
    '12-15',
    45,
    'Finish with glutes, not your low back.'
  ),
  (
    'core-workout',
    'ab-roller',
    'Core',
    'Main work',
    1,
    '3',
    '6-10',
    60,
    'Only roll as far as you can while keeping the trunk braced.'
  ),
  (
    'core-workout',
    'ab-crunch-machine',
    'Core',
    'Main work',
    2,
    '3',
    '12-15',
    45,
    'Think about curling the ribs toward the pelvis.'
  ),
  (
    'core-workout',
    'cable-crunch',
    'Core',
    'Main work',
    3,
    '3',
    '10-15',
    45,
    'Move the torso, not just the arms.'
  ),
  (
    'core-workout',
    'hanging-leg-raise',
    'Core',
    'Accessories',
    4,
    '3',
    '8-12',
    60,
    'Control the swing and use the abs to lift.'
  ),
  (
    'core-workout',
    'plank',
    'Core',
    'Accessories',
    5,
    '3',
    '30-45 sec',
    30,
    'Stay long through the body and keep the glutes tight.'
  ),
  (
    '30-minute-fat-loss-workout',
    'goblet-squat',
    'Circuit',
    'Circuit A',
    1,
    '3',
    '10-12',
    30,
    'Keep the pace honest but controlled.'
  ),
  (
    '30-minute-fat-loss-workout',
    'pushups',
    'Circuit',
    'Circuit A',
    2,
    '3',
    '6-12',
    30,
    'Elevate hands if needed to stay in range.'
  ),
  (
    '30-minute-fat-loss-workout',
    'bent-over-two-dumbbell-row',
    'Circuit',
    'Circuit A',
    3,
    '3',
    '10-12',
    30,
    'Pause briefly at the top.'
  ),
  (
    '30-minute-fat-loss-workout',
    'bodyweight-walking-lunge',
    'Circuit',
    'Circuit B',
    4,
    '3',
    '10 each side',
    30,
    'Keep every rep balanced.'
  ),
  (
    '30-minute-fat-loss-workout',
    'mountain-climbers',
    'Circuit',
    'Circuit B',
    5,
    '3',
    '20-30 sec',
    30,
    'Stay braced instead of bouncing around.'
  ),
  (
    '30-minute-fat-loss-workout',
    '3-4-sit-up',
    'Circuit',
    'Core',
    6,
    '2-3',
    '12-15',
    30,
    'Use a steady pace.'
  ),
  (
    'walking-and-strength-workout',
    'goblet-squat',
    'Strength block',
    'Main work',
    1,
    '3',
    '10-12',
    60,
    'Use a load you can control cleanly.'
  ),
  (
    'walking-and-strength-workout',
    'dumbbell-bench-press',
    'Strength block',
    'Main work',
    2,
    '3',
    '8-10',
    75,
    'Stay planted and stable.'
  ),
  (
    'walking-and-strength-workout',
    'bent-over-two-dumbbell-row',
    'Strength block',
    'Main work',
    3,
    '3',
    '10-12',
    60,
    'Keep the torso angle consistent.'
  ),
  (
    'walking-and-strength-workout',
    'bodyweight-walking-lunge',
    'Strength block',
    'Accessories',
    4,
    '2-3',
    '10 each side',
    45,
    'Control each step.'
  ),
  (
    'walking-and-strength-workout',
    'plank',
    'Strength block',
    'Core',
    5,
    '3',
    '20-40 sec',
    30,
    'Brace hard for each hold.'
  ),
  (
    'low-impact-workout',
    'chair-squat',
    'Main Session',
    'Main work',
    1,
    '3',
    '10-15',
    45,
    'Use the chair as a target and stay smooth.'
  ),
  (
    'low-impact-workout',
    'dumbbell-bench-press',
    'Main Session',
    'Main work',
    2,
    '3',
    '8-10',
    60,
    'Use a light, controlled load.'
  ),
  (
    'low-impact-workout',
    'seated-cable-rows',
    'Main Session',
    'Main work',
    3,
    '3',
    '10-12',
    60,
    'Sit tall and avoid jerking the handle.'
  ),
  (
    'low-impact-workout',
    'dumbbell-step-ups',
    'Main Session',
    'Accessories',
    4,
    '2-3',
    '8-10 each side',
    60,
    'Use a low step and stay balanced.'
  ),
  (
    'low-impact-workout',
    '3-4-sit-up',
    'Main Session',
    'Core',
    5,
    '2-3',
    '10-12',
    30,
    'Keep the movement controlled.'
  ),
  (
    'hotel-gym-workout',
    'dumbbell-squat',
    'Hotel Session',
    'Main work',
    1,
    '3',
    '10-12',
    60,
    'Use the best load the hotel gym has available.'
  ),
  (
    'hotel-gym-workout',
    'dumbbell-bench-press',
    'Hotel Session',
    'Main work',
    2,
    '3',
    '8-12',
    75,
    'Keep the rep quality high.'
  ),
  (
    'hotel-gym-workout',
    'bent-over-two-dumbbell-row',
    'Hotel Session',
    'Main work',
    3,
    '3',
    '10-12',
    60,
    'Stay braced and row evenly.'
  ),
  (
    'hotel-gym-workout',
    'dumbbell-shoulder-press',
    'Hotel Session',
    'Accessories',
    4,
    '2-3',
    '10-12',
    60,
    'Use a controlled press.'
  ),
  (
    'hotel-gym-workout',
    'dumbbell-lunges',
    'Hotel Session',
    'Accessories',
    5,
    '2-3',
    '8-10 each side',
    45,
    'Keep every step balanced.'
  ),
  (
    'hotel-gym-workout',
    'plank',
    'Hotel Session',
    'Core',
    6,
    '2-3',
    '20-40 sec',
    30,
    'Brace and breathe.'
  ),
  (
    'busy-schedule-3-day-workout',
    'goblet-squat',
    'Day 1',
    'Main work',
    1,
    '3',
    '8-10',
    75,
    'Start the week with a lower-body anchor.'
  ),
  (
    'busy-schedule-3-day-workout',
    'dumbbell-bench-press',
    'Day 1',
    'Main work',
    2,
    '3',
    '8-10',
    75,
    'Keep the bench press simple and repeatable.'
  ),
  (
    'busy-schedule-3-day-workout',
    'romanian-deadlift',
    'Day 2',
    'Main work',
    3,
    '3',
    '8-10',
    90,
    'Train the hinge with control.'
  ),
  (
    'busy-schedule-3-day-workout',
    'bent-over-two-dumbbell-row',
    'Day 2',
    'Main work',
    4,
    '3',
    '10-12',
    60,
    'Focus on consistent range.'
  ),
  (
    'busy-schedule-3-day-workout',
    'bodyweight-walking-lunge',
    'Day 3',
    'Main work',
    5,
    '3',
    '10 each side',
    45,
    'A short session can still be productive.'
  ),
  (
    'busy-schedule-3-day-workout',
    'dumbbell-shoulder-press',
    'Day 3',
    'Main work',
    6,
    '3',
    '8-10',
    60,
    'Finish the week with a stable upper-body push.'
  ),
  (
    'beginner-strength-program',
    'barbell-squat',
    'Day A',
    'Primary lifts',
    1,
    '3',
    '5',
    180,
    'Keep these working sets strong but submaximal.'
  ),
  (
    'beginner-strength-program',
    'barbell-bench-press-medium-grip',
    'Day A',
    'Primary lifts',
    2,
    '3',
    '5',
    180,
    'Use a consistent setup and pause lightly if needed.'
  ),
  (
    'beginner-strength-program',
    'bent-over-barbell-row',
    'Day A',
    'Assistance',
    3,
    '3',
    '6-8',
    120,
    'Stay braced through every set.'
  ),
  (
    'beginner-strength-program',
    'barbell-deadlift',
    'Day B',
    'Primary lifts',
    4,
    '3',
    '3-5',
    180,
    'Pull from a stable start and keep technique identical.'
  ),
  (
    'beginner-strength-program',
    'barbell-shoulder-press',
    'Day B',
    'Primary lifts',
    5,
    '3',
    '5',
    150,
    'Press from a tight midline.'
  ),
  (
    'beginner-strength-program',
    'wide-grip-lat-pulldown',
    'Day B',
    'Assistance',
    6,
    '3',
    '8-10',
    75,
    'Use a full range and control the return.'
  ),
  (
    'powerlifting-beginner-program',
    'barbell-squat',
    'Day 1',
    'Competition lifts',
    1,
    '4',
    '4-6',
    180,
    'Main squat practice day.'
  ),
  (
    'powerlifting-beginner-program',
    'bench-press-powerlifting',
    'Day 1',
    'Competition lifts',
    2,
    '4',
    '4-6',
    180,
    'Use a meet-style setup.'
  ),
  (
    'powerlifting-beginner-program',
    'barbell-deadlift',
    'Day 2',
    'Competition lifts',
    3,
    '4',
    '3-5',
    180,
    'Prioritize clean start positions.'
  ),
  (
    'powerlifting-beginner-program',
    'barbell-shoulder-press',
    'Day 2',
    'Support work',
    4,
    '3',
    '5-6',
    120,
    'Build pressing strength without overcomplicating it.'
  ),
  (
    'powerlifting-beginner-program',
    'bench-press-powerlifting',
    'Day 3',
    'Competition lifts',
    5,
    '4',
    '5-6',
    150,
    'Slightly higher bench volume day.'
  ),
  (
    'powerlifting-beginner-program',
    'bent-over-barbell-row',
    'Day 3',
    'Support work',
    6,
    '3',
    '6-8',
    120,
    'Back strength still matters for the total.'
  ),
  (
    'squat-focused-workout',
    'barbell-squat',
    'Squat Focus',
    'Primary lifts',
    1,
    '5',
    '3-5',
    180,
    'Main strength focus for the day.'
  ),
  (
    'squat-focused-workout',
    'front-barbell-squat',
    'Squat Focus',
    'Primary lifts',
    2,
    '3',
    '4-6',
    150,
    'Keep the torso tall and clean.'
  ),
  (
    'squat-focused-workout',
    'leg-press',
    'Squat Focus',
    'Secondary work',
    3,
    '3',
    '8-12',
    90,
    'Drive hard but stay controlled.'
  ),
  (
    'squat-focused-workout',
    'romanian-deadlift',
    'Squat Focus',
    'Secondary work',
    4,
    '3',
    '6-8',
    120,
    'Balance the day with posterior-chain work.'
  ),
  (
    'squat-focused-workout',
    'leg-extensions',
    'Squat Focus',
    'Accessories',
    5,
    '3',
    '12-15',
    60,
    'Finish with controlled quad volume.'
  ),
  (
    'bench-press-focused-workout',
    'bench-press-powerlifting',
    'Bench Focus',
    'Primary lifts',
    1,
    '5',
    '3-5',
    180,
    'Use your strongest repeatable competition-style setup.'
  ),
  (
    'bench-press-focused-workout',
    'close-grip-barbell-bench-press',
    'Bench Focus',
    'Primary lifts',
    2,
    '3',
    '5-6',
    150,
    'Secondary strength builder for triceps.'
  ),
  (
    'bench-press-focused-workout',
    'barbell-incline-bench-press-medium-grip',
    'Bench Focus',
    'Secondary work',
    3,
    '3',
    '6-8',
    120,
    'Build the upper chest and shoulders.'
  ),
  (
    'bench-press-focused-workout',
    'flat-bench-cable-flyes',
    'Bench Focus',
    'Secondary work',
    4,
    '3',
    '12-15',
    45,
    'Keep the chest working through the whole range.'
  ),
  (
    'bench-press-focused-workout',
    'reverse-grip-triceps-pushdown',
    'Bench Focus',
    'Accessories',
    5,
    '3',
    '10-12',
    45,
    'Finish with direct triceps work.'
  ),
  (
    'deadlift-focused-workout',
    'barbell-deadlift',
    'Deadlift Focus',
    'Primary lifts',
    1,
    '5',
    '3-5',
    180,
    'Treat the first pull of every set like a single.'
  ),
  (
    'deadlift-focused-workout',
    'romanian-deadlift',
    'Deadlift Focus',
    'Primary lifts',
    2,
    '3',
    '6-8',
    150,
    'Use this for tension and position, not sloppy fatigue.'
  ),
  (
    'deadlift-focused-workout',
    'bent-over-barbell-row',
    'Deadlift Focus',
    'Secondary work',
    3,
    '3',
    '6-8',
    120,
    'Build the upper-back support system.'
  ),
  (
    'deadlift-focused-workout',
    'wide-grip-lat-pulldown',
    'Deadlift Focus',
    'Secondary work',
    4,
    '3',
    '8-10',
    75,
    'Train the lats through a full range.'
  ),
  (
    'deadlift-focused-workout',
    'hyperextensions-back-extensions',
    'Deadlift Focus',
    'Accessories',
    5,
    '3',
    '10-15',
    60,
    'Use bodyweight or a small plate to finish.'
  ),
  (
    'strength-and-hypertrophy-workout',
    'barbell-bench-press-medium-grip',
    'Upper',
    'Strength work',
    1,
    '4',
    '4-6',
    150,
    'Strength emphasis starts here.'
  ),
  (
    'strength-and-hypertrophy-workout',
    'bent-over-barbell-row',
    'Upper',
    'Strength work',
    2,
    '4',
    '5-6',
    150,
    'Pair heavy upper-body pulling with the press.'
  ),
  (
    'strength-and-hypertrophy-workout',
    'side-lateral-raise',
    'Upper',
    'Hypertrophy work',
    3,
    '3',
    '12-15',
    45,
    'Controlled delt volume.'
  ),
  (
    'strength-and-hypertrophy-workout',
    'barbell-squat',
    'Lower',
    'Strength work',
    4,
    '4',
    '4-6',
    180,
    'Use this as the main lower-body strength anchor.'
  ),
  (
    'strength-and-hypertrophy-workout',
    'barbell-deadlift',
    'Lower',
    'Strength work',
    5,
    '3',
    '3-5',
    180,
    'Heavy pulls with clean technique.'
  ),
  (
    'strength-and-hypertrophy-workout',
    'leg-press',
    'Lower',
    'Hypertrophy work',
    6,
    '3',
    '10-12',
    90,
    'Add muscular volume without chasing sloppy reps.'
  );

insert into public.workout_template_exercises (
  workout_template_id,
  template_id,
  exercise_id,
  exercise_name,
  day_label,
  section,
  sort_order,
  sets,
  reps,
  rest_seconds,
  notes
)
select
  workout_templates.id,
  workout_templates.id,
  exercises.id,
  exercises.name,
  seed_workout_template_exercises.day_label,
  seed_workout_template_exercises.section,
  seed_workout_template_exercises.sort_order,
  seed_workout_template_exercises.sets,
  seed_workout_template_exercises.reps,
  seed_workout_template_exercises.rest_seconds,
  seed_workout_template_exercises.notes
from seed_workout_template_exercises
join public.workout_templates
  on workout_templates.slug = seed_workout_template_exercises.workout_template_slug
join public.exercises
  on exercises.slug = seed_workout_template_exercises.exercise_slug;

commit;
