-- Generated by website/scripts/generate-legal-archive.ts. Do not edit hashes manually.

begin;

do $legal_snapshot$
begin
  if exists (
    select 1
    from public.legal_document_versions as current_version
    join (values
  ('terms_of_service', '2026-08-20', '2026-08-20'::date, '3fb0e59316aac7a28f74cbf2ab574dec570d83e51ea0f08b6a56159134ee5308', '/legal/archive/terms/2026-08-20.html'),
  ('privacy_policy', '2026-08-20', '2026-08-20'::date, 'ccd40ed1462393629ace1ff25ed02218c61c55f5dc678c1553bc26263193c2e9', '/legal/archive/privacy/2026-08-20.html')
    ) as expected(document_key, version, effective_date, content_sha256, archive_path)
      on expected.document_key = current_version.document_key
      and expected.version = current_version.version
    where current_version.effective_date is distinct from expected.effective_date
      or current_version.content_sha256 is distinct from expected.content_sha256
      or current_version.archive_path is distinct from expected.archive_path
  ) then
    raise exception 'An existing legal document version differs from the immutable release snapshot.';
  end if;
end
$legal_snapshot$;

insert into public.legal_document_versions (
  document_key,
  version,
  effective_date,
  content_sha256,
  archive_path
)
values
  ('terms_of_service', '2026-08-20', '2026-08-20'::date, '3fb0e59316aac7a28f74cbf2ab574dec570d83e51ea0f08b6a56159134ee5308', '/legal/archive/terms/2026-08-20.html'),
  ('privacy_policy', '2026-08-20', '2026-08-20'::date, 'ccd40ed1462393629ace1ff25ed02218c61c55f5dc678c1553bc26263193c2e9', '/legal/archive/privacy/2026-08-20.html')
on conflict (document_key, version) do nothing;

update public.user_legal_acceptances as acceptance
set legal_document_version_id = version.id
from public.legal_document_versions as version
where version.document_key = acceptance.document_key
  and version.version = acceptance.document_version
  and acceptance.legal_document_version_id is distinct from version.id;

update public.user_legal_acceptance_history as history
set terms_document_version_id = version.id
from public.legal_document_versions as version
where history.terms_version = version.version
  and version.document_key = 'terms_of_service'
  and history.terms_document_version_id is distinct from version.id;

update public.user_legal_acceptance_history as history
set privacy_document_version_id = version.id
from public.legal_document_versions as version
where history.privacy_version = version.version
  and version.document_key = 'privacy_policy'
  and history.privacy_document_version_id is distinct from version.id;

commit;
